### ISSUE TITLE
[makeotfexe] makeotfexe produces incorrect output for bug1006/feat.fea

### ISSUE THREAD

**Issue by cjchapman** [adobe-type-tools/afdko#1010]
I think that `makeotfexe` might be producing incorrect output for [bug1006/feat.fea](https://github.com/adobe-type-tools/afdko/blob/develop/tests/makeotfexe_data/input/bug1006/feat.fea). See the TTX dump of the GPOS table produced by it in [bug1006.ttx](https://github.com/adobe-type-tools/afdko/blob/develop/tests/makeotfexe_data/expected_output/bug1006.ttx).

Here's a more complete version of the feature file, including a `GSUB` lookup to produce the `c_t` ligature:

```fea
markClass [acute grave] <anchor 500 700> @TOP_MARKS;
lookup test {
    pos ligature c c_t' t <anchor 500 800> mark @TOP_MARKS
        ligComponent <anchor 1500 800> mark @TOP_MARKS;
} test;
lookup ctlig {
    substitute  c t by c_t;
} ctlig;
feature mark {
    lookup test;
} mark;
feature rlig {
    lookup ctlig;
} rlig;
```

**Comment by cjchapman** [comment]
@readroberts Can you please check if the current output is correct and update this record with your conclusion? Thanks!

**Comment by readroberts** [comment]
Definitely not right.  Will look at code to see what's up.

**Comment by cjchapman** [comment]
@readroberts Thanks!

**Comment by readroberts** [comment]
makeotfexe is producing correct output for the current feature file, and this is still a good test for making a simple contextual mark to ligature lookup. However, the feature file is not effective at actually doing layout. In order to be useable, the feature file would need a 'liga' feature to make the c_t glyph, as noted above, but also the contextual input sequence needs to include the expected mark glyphs sequences, and the mark-to-ligature lookup needs to be referenced after each mark glyph.
