### ISSUE TITLE
[makeotfexe] Unicode not assigned if hex value has lowercase letter

### ISSUE THREAD

**Issue by benkiel** [adobe-type-tools/afdko#1027]
Ran into this when double mapping:

`uni004a` won't assign a unicode value, `uni004A` will. 

Unsure if this is expected behavior.

**Comment by cjchapman** [comment]
The exclusion of lower case hex digits is explicitly encoded:

https://github.com/adobe-type-tools/afdko/blob/eac1fff5f6ca03466f956e8901121c874ea66c7a/c/makeotf/makeotf_lib/source/hotconv/map.c#L1412-L1415

So it is by design, at least.

As far as expected, I dunno. The only advantage I could see is differentiating `uniface` (a type of stone tool) from `uniFACE` (a CJK ideograph). (I'm at a loss for an equivalent scenario with the `uXXXX` names.) Since this is unlikely to be a problem, I'm open to removing the restriction.

@readroberts Am I missing something, or do you think we could remove the requirement for the hex digits to be uppercase?

**Comment by benkiel** [comment]
I hit this because I was pulling unicode values from python (`f"{glyph.unicode:04x}"`) and forgot to uppercase the hex (`f"{glyph.unicode:04X}"`). I'm fine if this is how it is, but it should be documented (happy to do so).

**Comment by cjchapman** [comment]
@josh-hadley and I were just talking about this, and we concluded that it's best to leave the code as it is, and yes, document it. So, @benkiel, we'll happily take you up on your offer to document it. Thanks!
