### ISSUE TITLE
makeotf user guide partly broken in .io view

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1087]
I don’t know if this is a GitHub issue or not:

This table looks broken:
http://adobe-type-tools.github.io/afdko/MakeOTFUserGuide.html#makeotf-options
This looks fine:
https://github.com/adobe-type-tools/afdko/blob/develop/docs/MakeOTFUserGuide.md#makeotf-options

**Comment by josh-hadley** [comment]
Might be something with attempting to style the table columns. Looking at the HTML, it treats the broken table as a `<p>` with an opening double-quote. There are double quotes inside the styling directives, so might be something to do with that. I'll see if I can work out what's going on.

**Comment by josh-hadley** [comment]
Apparently there are some differences between how github.com renders Markdown versus what github.io converts to HTML and serves. I've removed what I believe to be the offending stuff, and made a few more minor edits to the table, which should fix this. But it won't be seen on the github.io version until the next release, because github.io is served out of `master/docs`, not `develop`.
