### ISSUE TITLE
[makeotf] CFF FontBBox miscalculated for upm != 1000

### ISSUE THREAD

**Issue by jenskutilek** [adobe-type-tools/afdko#111]
The FontBBox in the CFF table seems to be always calculated relative to 1000 upm.

I have a font with 2000 upm, and the FontBBox values are about half the size they should be.

This is visible in InDesign, where the selection and cursor are drawn too small when the font is active.

**Comment by miguelsousa** [comment]
@jenskutilek can you provide more details about your process? What's the format of the source font? How was it generated? What FDK tool you used?

I distinctively recall getting Type 1 (.pfa) fonts with a wrong FontBBox from FontLab, whenever the UPM value was not 1000. Don't know if that bug has been fixed in recent versions.

**Comment by jenskutilek** [comment]
Thanks for the suggestion, Miguel. The source font is indeed a pfa from FontLab, and the FontBBox is miscalculated there already.

I will try to use an OTF as source font.
