### ISSUE TITLE
WOFF2 support in AFDKO

### ISSUE THREAD

**Issue by twardoch** [adobe-type-tools/afdko#113]
On the [FontLab forum](http://forum.fontlab.com/adobe-fdk-for-opentype-(afdko)/how-to-integrate-brotli-python-extension-into-afdko/new/#new), Arno Enslin asks: 

.....
From subset (belonging to the FontTools, that are integrated in the AFDKO) help:

  --flavor=<type>
      Specify flavor of output font file. May be 'woff' or 'woff2'.
      Note that WOFF2 requires the Brotli Python extension, available
      at https://github.com/google/brotli

Can anybody explain, how I can integrate that extension into the AFDKO?
.....

That's an interesting question, actually. AFDKO does use fontTools in some aspects, but I'm not sure exactly to what extent. fontTools.ttLib can now optionally read and write WOFF2, and perhaps this is something that could be integrated into AFDKO (tx, makeOTF)?

**Comment by benkiel** [comment]
WOFF and WOFF2 are post processing steps to a OTF/TTF, no?

It seems possible for the ADFKO to make WOFF/WOFF2, but it also doesn't seem to quite align with what the FDK is to do, which is to add tables to a source to make a OTF or TTF with OpenType features. 

In my view, making web fonts is a separate thing.

**Comment by kenlunde** [comment]
This smells akin to the situation of building Font Collections, specifically that it doesn't make much sense for _makeotf_ to emit them, but that it is a task best left to a dedicated tool that is a executed as a post-process on OTFs or TTFs. That is what the _otf2otc_ script does, and does quite nicely. Whether WOFF/WOFF2 conversion tools should be included in AFDKO seems to be the better consideration to ponder.

**Comment by anthrotype** [comment]
> ... what the FDK is to do, which is to add tables to a source to make a OTF or TTF with OpenType features

Well, that's the purpose of makeotf, which is only one among the several tools included in the AFDKO.
I think Adam was not suggesting to add an option to makeotf to export to WOFF2, but rather to include the google brotli python extension module in the AKFDO python distribution (https://github.com/google/brotli). This would be enough to allow the included fontTools/TTX to read/write WOFF2 files.

**Comment by benkiel** [comment]
@anthrotype Adam suggested adding it to tx and/or makeotf in the last sentence of his issue, hence my comment.

**Comment by anthrotype** [comment]
@benkiel you're right, sorry :)

I think it'd be already something if brotli was packaged in the AFDKO distribution. The user that Adam quoted was trying to use the fonttools subsetter.

**Comment by twardoch** [comment]
Adding woff(2) to tx was just my loose idea. Indeed primarily the postulate would be to bundle fontTools along with brotli in the release FDK.

**Comment by kenlunde** [comment]
@twardoch: The AFDKO _tx_ tool operates on a small subset of the sfnt tables, so it would be a very inappropriate vehicle for WOFF/WOFF2 conversion. I favor a dedicated tool/script for that purpose.

**Comment by twardoch** [comment]
Yes, I principally agree. The main point is that ge binary FDK distros are useful in that they also bundle fontTools. Modern fontTools have an optional dependancy on brotli which for unexperienced users esp. on Windows is tedious to build, so prebuilding it and bundling it with FDK-provided fontTools would make sense. 

I agree that extending `tx` to read WOFF or WOFF2-packaged SFNT may be a bit too much — though I principally don’t see much difference in having the ability to manipulate the `CFF ` table regardless of whether it’s packaged inside an .otf, .woff or .woff2 container. 

Keep in mind that WOFF2 is being adopted for more and more for “desktop” use — it’s simply an efficiently-compressed packaging of the entire SFNT container, somewhat similar to what CFF is for Type 1. Once WOFF2 is finalized, there’ll be nothing wrong in adopting it for use as a format for installable fonts (esp. in mobile or embedded contexts), for e-book or other document embedding.

**Comment by readroberts** [comment]
I will certainly add the brotli module to the next public build of the AFDKO that I post on the Adobe web site. A semantic quibble: I won't add fontTools to the OpenSource AFDKO because it it a one of the several third party components that must be added in order to make it fully functioning, and I'd rather developers got the third party stuff straight from the source. I think adding WOFF export/import/merge between font files and XML will be trivial as it supported by fontTools + brotli in the form of the 'ttx' command, and fontTools and ttx are already in the built-out AFDKO. Adding 'brotli' to the current FDK download is simple: simply use the built-in FDK Python interpreter to install the latest branch of fontTools and brotli, and you should be good to go.

**Comment by readroberts** [comment]
I've been trying to help Arno Eslin get brotli added to the AFDKO under Windows. Just running 'ttx -h', without brotli, he gets an error:
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x000000000232B668> ignored

Anyone else seen this? I can't immediately duplicate it on my Windows virtual machine.

**Comment by twardoch** [comment]
Read, 
unfortunately, I haven't seen this problem. But I agree — the opensource FDK repo shouldn't include a duplicate copy of fontTools. I only suggested prepackaging brotli with the "binary" distributables. The github repo is fine as it is :)

**Comment by readroberts** [comment]
PS. In working with Arno, I saw that you cannot simply install the latest fontTools into the AFDKO with the usual 'AFDKO setup.py install" command, as the older AFDKO FontTools version has a different dir name: you should first manually delete the old FontTools dir and FontTools.pth  file, then install the new stuff. The order doesn't really matter - I delete the older fontTools first only because it is easier to delete all FontTools items than to think about which are the old ones.

**Comment by anthrotype** [comment]
If you're still having this issue, could you please forward it to the fonttools github issue tracker? Thank you.

**Comment by Arno-Enslin** [comment]
I meanwhile have Brotli and Zopfli added. And with TTX it is easy to generate woff and woff2. But TTX decompiles OTF and TTF first. So this way of compression/decompression is not losless in case of woff. (Woff2 is lossy anyway. So this doesn't matter.)

But as far as I know, Brotli can take a few arguments, namely  "--quality n", " --force" and "--verbose". And the quality argument is interesting. With TTX I haven't access to that argument.

I have woff(2)-(de)compress binaries, I would prefer to compress and decompress with Brotli and Zopfli integrated in the AFDKO and without decompiling, but just generating, because than it is easier to make use of the latest compression algorithms / versions of the tools. (I had asked a friend for building the binaries for me.)

------------------------------------

By the way, there is a bug in ttxn.py again. It doesn't work with the latest FontTools.

And the BuildAll command does work only, if you install Visual Studio 2010 on Windows 7. This information should be added to the FDK Build Notes.

**Comment by anthrotype** [comment]
> TTX decompiles OTF and TTF first. So this way of compression/decompression is not lossless in case of woff. 

Right. I guess that's the reason you want to add an option to ttx script to [dump tables as hex data](https://github.com/behdad/fonttools/issues/560).

Since there seems to be some demand for it, I think we could add a separate tool (i.e. "pyftconvert") that only does the conversion between different "flavors", so one doesn't need to first decompile/dump the font to TTX, or use pyftsubset to do that (/cc @behdad).

In the meantime, you could write very simple python scripts that load a TTFont, set the `flavor` attribute to the "woff" or "woff2", and save the new converted font.
For woff2, I put two sample scripts in fonttools' Snippets folder:
https://github.com/behdad/fonttools/blob/master/Snippets/woff2_compress.py
https://github.com/behdad/fonttools/blob/master/Snippets/woff2_decompress.py

**Comment by anthrotype** [comment]
> Brotli can take a few arguments, namely "--quality n", " --force" and "--verbose". And the quality argument is interesting. With TTX I haven't access to that argument.

Currently, fonttools compresses WOFF2 fonts using the highests (which is also the default) brotli "quality", i.e. 11. I could add an option to set a lower quality (=> greater file size but slightly faster compression).

> I would prefer to compress and decompress with Brotli and Zopfli ...

I seems like you implying that one could simply take a TTF and zip it with Zopfli or Brotli to obtain a WOFF or WOFF 2 font. I'm afraid it's not that easy. :)
Brotli, zlib, Zopfli etc. are general-purpose compression libraries which are also used in font formats like WOFF 1/2 to encode specific parts of their data.

**Comment by Arno-Enslin** [comment]
>Right. I guess that's the reason you want to add an option to ttx script to dump tables as hex data.

No. Answer in [#560](https://github.com/behdad/fonttools/issues/560).

**Comment by behdad** [comment]
> Since there seems to be some demand for it, I think we could add a separate tool (i.e. "pyftconvert") that only does the conversion between different "flavors", so one doesn't need to first decompile/dump the font to TTX, or use pyftsubset to do that (/cc @behdad).

Or just make ttx be able to read binary and write binary.  Ie, ttf -> woff2.  Right now ttx is binary->xml and xml->binary only.  No need to be that way.  In fact, xml->xml is also useful for testing the library itself.  I have a 2-line script that does that :).

**Comment by Arno-Enslin** [comment]
anthrotype's snippets work fine. It was easy to modify them for woff.

woff_and_woff2_decompress.py
woff_compress_Pure_Zlib.py
woff_compress_with_Zopfli.py
woff2_compress.py

It would be nice, if I could generate EOT to without EOTfast. But there is only a EOT lite module for Python as far as I know. Is this correct?

**Comment by anthrotype** [comment]
> But there is only a EOT lite module for Python as far as I know. Is this correct?

there's also Google's [sfntly](https://github.com/googlei18n/sfntly), which is mainly written in Java, and has support for compressing EOT using Microtype Express (MTX).

Some time ago, I had written a shallow python wrapper that simply runs the sftnly's `sfnttool.jar` as a subprocess. You can grab it here: https://github.com/daltonmaag/sfntly-py

**Comment by anthrotype** [comment]
Note that we do have plans to add support for EOT in fontTools in the coming months. 
I started writing Python bindings for lzcomp compression here: https://github.com/anthrotype/lzcomp.
We still need to write the EOT reader and writer. Although I don't see that as a big priority..

**Comment by Arno-Enslin** [comment]
No, I will wait, till FontTools support EOT. I had to install Java for sfntly. If it would be needed for the build process only, I would think about installing Java.

**Comment by readroberts** [comment]
'brotli' is now included in the FDK public release build.

**Comment by Arno-Enslin** [comment]
Zopfli too?

**Comment by Arno-Enslin** [comment]
May it be, that you have not integrated Zopfli [because of this issue](https://github.com/google/zopfli/issues/115)?

**Comment by readroberts** [comment]
No, only because I didn't realize that there was a need to add the zopfli library.. I think it reasonable to add zopfli as well as brotli, since zopfli is used to build WOFF files, but since the github repository doesn't include a full set of build instructions or make files for all the platforms, nor a setup.py script to install the library once it is built, I will put this off until I have more time.

**Comment by Arno-Enslin** [comment]
I thought, this is easy on all platforms with anthrotype's [py-zopfli](https://github.com/anthrotype/py-zopfli). It includes a setup.py.
