### ISSUE TITLE
[spec] Includes not ending in semicolon

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#114]
It seems that `makeotf` allows include statements not ending with semicolons, e.g.:

```
include (markclasses.fea)
```

But the spec does not document this, so two questions:
- Is this a bug or an undocumented feature?
- What happens if other feature code is present in the same line, e.g.

```
include (markclasses.fea) feature foo {} foo;
```

**Comment by readroberts** [comment]
The spec does show that an include statement should be terminated by a semi-colon. I would like to keep it this way. Unfortunately, there are a lot of old source files in the AdobeType library whcihdoes not terminate with a semi-colon. I will change makeotf to issue a warning, to discourage this practice, but not a fatal error. 
If someone really wants to add more definitions after a feature file include statement that is missing a semi-colon, I would issue a warning, but otherwise behave as if there were a semi-colon after the include statement.

**Comment by khaledhosny** [comment]
Thanks for explanation.

**Comment by frankrolf** [comment]
In my opinion, it makes sense for `include (file.fea)` statements not to end in a semicolon, because the contents of `file.fea` most likely does.

Consider the contents of the following `file.fea`:
```
feature smcp { 
sub [a-z] by [a.sc-z.sc];
} smcp;
```

The statement `include (file.fea);` would basically create:
```
feature smcp { 
sub [a-z] by [a.sc-z.sc];
} smcp;;
```
(note last semicolon)

**Comment by khaledhosny** [comment]
Unless the parser “consumes” the semicolon after parsing the include statement, which is the logical thing to do.

**Comment by readroberts** [comment]
Khaled is correct; the parser consumes the terminating semicolon, if it is present.

**Comment by miguelsousa** [comment]
The warning was added in 49527cd0cb65982e0151571c2df631389ba900ee
