### ISSUE TITLE
[makeinstancesufo] no longer allows extrapolation

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1152]
When explaining the principles of interpolation to students today, I noticed that the tool no longer allows instance values that go beyond the defined axis extremes (e.g. `-200`  in a `0` - `1000` axis).

The result in the above case is just an instance of interpolation value 0 (no complaints from `makeinstancesufo`)

I know extrapolation is not a typical use case, but it is allowed by mutator and great for demonstration and exploration. Could this change have happened with the addition of varLib in 7f09153068ec05e9b1c07a133edd2a068da1bab7 ?

**Comment by josh-hadley** [comment]
Ohh...yes, quite possibly. I think @punchcutter should check/confirm but I think this:
https://github.com/adobe-type-tools/afdko/commit/7f09153068ec05e9b1c07a133edd2a068da1bab7#diff-f2284e0a884b16cdbcc94dd2fea1d2caR416

...should probably be `store_true` instead of `store_false`. @frankrolf try running your command with `--useVarlib`, which sounds counter-intuitive, but with the current implementation, it means _don't_ use varLib (set `useVarLib` to `False`) which should use MM and re-enable extrapolation. If that works, then definitely the above line is the issue and should be changed to `store_true`.

**Comment by punchcutter** [comment]
Oh, that's not right. Guess I'd better check those tests again, too.

**Comment by frankrolf** [comment]
Confirming that the `--use-varlib` option yields the result expected from Mutator.
`True` ¯\_(ツ)_/¯ `False`
