### ISSUE TITLE
RFC: Updating the AFM spec to support variable fonts

### ISSUE THREAD

**Issue by Alhadis** [adobe-type-tools/afdko#1217]
> _Apologies if this repository isn't the right place to file this… I couldn't find a more relevant-looking place to discuss the Adobe Font Metrics format. If there's somewhere more appropriate, please let me know._

Summary
-------
The Adobe Font Metrics format, [last updated in 1998][1], hasn't needed an update in over 20 years. With the recent arrival of variable fonts, however, it might be time to bump `v4.1` to a proposed `v5.0`. Major changes would include:

1. Support for variation axes in AFM files
2. Possible revisions to ACFM files to accommodate point #1.
3. Deprecation of the AMFM format (obsolete since ~1999)

Motivation
----------
Typesetting software such as [Heirloom Troff](http://n-t-roff.github.io/heirloom/doctools.html) uses `.afm` files for storing character metrics. Variable fonts—the best thing to happen to digital typography since hinting—are an obviously desirable addition to anything focussed on high-quality type. There's little reason to invent another metrics format: `.afm` files are easy to parse, extensible, widely-supported, and mostly self-documenting.

Suggested implementation
------------------------
Unlike AMFM, all masters and axes are included with the AFM data, keeping a one-to-one correspondence between the variable font and its `.afm` file.

~~~afm
StartFontMetrics 5.0
StartAxis wdth
AxisLabel width
Default 500
Range 0 1000
StartNamedInstances 3
A wdth ; N Bold   ; V 700 ;
A wdth ; N Thin   ; V 300 ;
A wdth ; N Normal ; V 500 ;
EndNamedInstances
StartVariationMetrics 855
C 35 ; PB 0 62.5 0 75.5 0 ; PB 500 12 0 12 0 ; PB 750 …
C 36 ; PB 0 62.5 0 75.5 0 ; PB 500 12 0 12 0 ; PB 750 …
EndVariationMetrics
EndAxis
~~~

Sidenotes
---------
*	`StartAxis` requires an argument: the axis's tag (which is mandatory anyway).
*	`Range`, `Default` and other "prologue" lines reflect similarly-named fields in [`.designspace` files][4].
*	Here, `PB` stands for the parameters `position` and `bounding-box`. Vertical and horizontal advance widths need to be considered too, so we'd also have `PWX`/`PW0X`/`PVX`/etc (cf. [§ 8 "Individual Character Metrics"][3]). A single `P` directive might offer a more concise representation to reduce filesize:
	~~~afm
	StartVariationMetrics 855
	Comment [pos] [bounding-box] [WX0] [WY1] etc
	C 35 ; P  0      12 0 12 0    512   512   … ;
	EndVariationMetrics
	~~~
*	The terms _"axis"_ and _"master"_ used in this RFC have no implied relation to Adobe's multiple-masters format (AMFM), which has been obsolete since ~1999. No known software—supported by Adobe or otherwise—supports `.amm` files. Hell, it was a challenge to even *find* one that wasn't [copied from the spec's examples][2].

[1]: https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5004.AFM_Spec.pdf "v4.1 / 1998"
[2]: https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5004.AFM_Spec.pdf#G3.694
[3]: https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5004.AFM_Spec.pdf#page=31
[4]: https://robofont.com/documentation/how-tos/creating-designspace-files/

**Comment by khaledhosny** [comment]
AFM/Type 1 is obsolete technology and no one is going to up date them, and this is not the right place to ask any way (there probably exists no such place anymore).

**Comment by josh-hadley** [comment]
Hi @Alhadis and thanks for this detailed proposal. While we can appreciate the need for the use case you mention, we will not be making any updates to the AFM specification.

**Comment by Alhadis** [comment]
> we will not be making any updates to the AFM specification.

Why?

**Comment by twardoch** [comment]
From my perspective (I'm not affiliated with Adobe):

AFM has severe limitations. For example, part of the AFM file is kerning, but kerning in AFM is limited to left-to-right glyph-to-glyph kerning. That may have been sufficient in Type 1, but today most font vendors make fonts for left-to-right, right-to-left and vertical typesetting, and all those directions can be mixed in one font. Also, OpenType uses class (group) kerning, for which AFM has no provisions. 

If you add variations to that, I can see that it would be a huge effort to think of a suitable format. And I don't see the benefit for Adobe. Adobe no longer uses AFM. It would only consume their resources, especially that creating a format documentation takes time, and such a format would have little value if it were not supported.  The Adobe Type team is a small group of experts, their time is not infinitely stretchable. Specs don't write themselves, and the Adobe experts have more than enough work on their hands.

Of course I think any interested parties are free to create a format based on AFM that could include data for variable fonts.

But formats without tool/app support also make little sense. AFM was created in times when Type 1 was a secret format. 

Today, the OpenType spec is publicly available, and there are tools and libraries in many programming languages that support even the more complex aspects of line layout and glyph rendering — C++, Java, JavaScript, Rust, Python and many others. Bindings to other languages are also available. 

In my humble opinion, the software you mention would benefit from adding direct support for OpenType, rather than relying on semi-solutions like the proposed extended AFM.

**Comment by twardoch** [comment]
I see that troff is written in C. FreeType is written in pure ANSI C, and HarfBuzz is written in C++ but can likely be transpiled to C via https://github.com/JuliaComputing/llvm-cbe or other such solutions.

With HarfBuzz and FreeType, a typesetting solution such as troff could be modernized. TeX has been using HarfBuzz in the LuaTeX and XeTeX projects (LuaTeX also now supports variable fonts), and it has proven to be a much more reliable solution.

**Comment by josh-hadley** [comment]
> > we will not be making any updates to the AFM specification.
> 
> Why?

@twardoch has the general idea here: we are supporting OpenType, and AFM is not part of OpenType.

**Comment by Alhadis** [comment]
I wasn't aware the AFM format itself was deprecated. This changes things. I guess it makes more sense to augment Troff's existing [width table](https://github.com/Mohamed-MIAGE/ProjetM1/blob/d1e06864e7b7f0794e15bf90070e57eac6e6e283/groff-1.22.3/font/devps/HR) format instead, then.

> I see that troff is written in C.

Troff isn't one program, it's several. They're designed to work independently of each other; the main `troff` binary emits an intermediate representation intended to be consumed by a format-specific driver (such as PDF, PostScript, plain text, etc). Due to the way the language is designed, it isn't a simple matter of just augmenting one program with OpenType support — *especially* when its predominant use nowadays is formatting man pages for terminal display (where everything is essentially fixed-pitch).

> TeX has been using HarfBuzz in the LuaTeX and XeTeX projects (LuaTeX also now supports variable fonts),

TeX and Troff are alike in function only. They're otherwise antipodal opposites in philosophy, design, and implementation.
