### ISSUE TITLE
Any reason why winAscent + winDescent can’t be smaller than the UPM?

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/afdko#1227]
https://github.com/adobe-type-tools/afdko/blob/5778828e0c1ac3c425a9c92c77f4a5bacf0d32bc/c/makeotf/makeotf_lib/source/hotconv/hot.c#L716-L721
This might be a good check for auto calculated winAscent + winDescent values. But quite confusing for manually set values.

**Comment by josh-hadley** [comment]
This code has been around for quite a while, probably with the same logic since the beginning. I don't think anyone is still around who was involved in the decisions on why it's done. I suspect it's rooted in the [OT spec recommendations around metrics and BTBD](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#baseline-to-baseline-distances) or something along those lines.

I would be open to the idea of changing this to detect-and-warn, without modifying any values. That way, anyone who is reliant on this behavior (knowingly or not) would at least be notified and make modifications to modify the values, if desired.
