### ISSUE TITLE
makeotf: synthesize UFO postscriptFontName if not present

### ISSUE THREAD

**Issue by frankrolf** [adobe-type-tools/afdko#1255]
`makeotf` has become quite user-friendly when it comes to generating fonts from any UFO file, everything just works like this:
```
makeotf -f my_font.ufo
```

However, if the UFO does not contain an entry for `postscriptFontName`, the process will fail:
```
makeotf [Error] Could not find 'postscriptFontName' in file '/Users/fgriessh/Desktop/my_font.ufo'
```

Could the PS name be synthesized if it’s missing? I imagine something simple like this:
```
ps_name = '-'.join((f.info.familyName, f.info.styleName)).replace(' ', '')
```

Of course, a note would be emitted if the name is created automatically.

**Comment by josh-hadley** [comment]
This seems like a perfectly reasonable thing to do. Could further fall back to "Unknown" if the `familyName` and `styleName` are somehow missing.

**Comment by josh-hadley** [comment]
OK, maybe _somewhat_ reasonable. Turns out the actual problem is in `tx`. `makeotf` is not actually reading the UFO _as a UFO_ -- it simply uses `tx` to dump the info and attempts to derive the psname from that. That part is easy enough to override in `makeotf`, but once that is obtained, `makeotf` again uses `tx` to convert to Type1 ("the only format that makeotf**exe** can consume"), and since the UFO will still not actually have a `postscriptFontName` at that point, it fails.

Ideas:
 - allow `makeotf` to modify the input UFO (re-write with a `postscriptFontName` key) before passing on to `tx` for Type1 conversion
 - have `makeotf` write a temporary `fontinfo` file that contains the `FontName` and modify the call to `tx` to use that (need to make sure that's even possible...)
 - modify `tx` to allow/synthesize a PSName in a similar manner as described above

@frankrolf any preference or other suggestions?

**Comment by frankrolf** [comment]
Thanks for looking into this @josh-hadley !
Option 3 sounds like the most elegant variant to me.

**Comment by josh-hadley** [comment]
I was afraid you might say that 😉  — it is probably the best way to do it, just slightly more painful than updating `makeotf.py`.

**Comment by miguelsousa** [comment]
I should mention that **tx** used to insert a **PSNameNotSpecified** string into UFOs lacking `postscriptFontName` (see #437) and that such approach had undesirable effects (see #282).

**Comment by josh-hadley** [comment]
> I should mention that **tx** used to insert a **PSNameNotSpecified** string into UFOs lacking `postscriptFontName` (see #437) and that such approach had undesirable effects (see #282).

Good to know! I think @frankrolf and I agreed that it should be possible to synthesize a real, useful name from the `familyName` and `styleName` elements that are more likely to be present in most UFOs, and only fall back to "Unknown" or "Unspecified" or whatever in the event that those aren't present (or maybe just error in that case).

I actually have some code written and working for this, but during some routine checks @cjchapman and I discovered some underlying memory-related bugs in `tx`'s handling of UFOs that are holding this up. It's functional though:

```
$ makeotf -f nopsfontname.ufo
tx: --- /Users/johadley/Desktop/nopsfontname.ufo
tx: (ufr)  ---> synthesized FontName: FamilyName-Regular
makeotf [Warning] Could not find default features file. Font will be built without any layout features.
Built development mode font '/Users/johadley/Desktop/FamilyName-Regular.otf'.
```

**Comment by miguelsousa** [comment]
Sounds good. Just make sure that the changes keep other input formats in parity (e.g. Type1 or OT font without PSName).

**Comment by miguelsousa** [comment]
The more I think about this (again) the more I think the "patching" should be done in **makeotf**.
What's the output of `tx -dump -0 nopsfontname.ufo` going to be, for example?

**Comment by josh-hadley** [comment]
> The more I think about this (again) the more I think the "patching" should be done in **makeotf**.

I'd like to do that also, but when I discussed this with @frankrolf he thought that modifying a user's input UFO data would be a big no-no. It would certainly be a lot easier to implement a solution by just patching up the UFO, but I think Frank was pretty strongly against that idea (note I did propose that above).

> What's the output of `tx -dump -0 nopsfontname.ufo` going to be, for example?

With the code I currently have:
```
$ tx -dump -0 nopsfontname.ufo
tx: --- nopsfontname.ufo
tx: (ufr)  ---> synthesized FontName: FamilyName-Regular
## Filename nopsfontname.ufo
## Top Dict
version             "1.0"
Notice              "This is a test font."
Copyright           "Copyright 2020 Adobe Systems Incorporated. All rights reserved."
FamilyName          "FamilyName"
sup.srcFontType     UFO (name-keyed)
sup.nGlyphs         1234
## FontDict[0]
FontName            "FamilyName-Regular"
## Private
```

**Comment by frankrolf** [comment]
I am completely open toward any approach, but I feel strongly against unexpected editing of user data. Why does the UFO need to be touched just to synthesize the PS name? Presumably that is a string stores somewhere – couldn't that happen within the makeotf tool itself?

**Comment by josh-hadley** [comment]
>Why does the UFO need to be touched just to synthesize the PS name?

`makeotf` calls `tx` to do the actual conversion, and `tx` has to convert the UFO into Type1 data first. That Type1 data _must_ have a psname; it's absolutely central to `tx`'s processing. So the string needs to be present in the input UFO, or `tx` has to be modified to synthesize it (or accept a param for it, whatever).

**Comment by miguelsousa** [comment]
> `FamilyName          "FamilyName"`

This is misleading. I'm not in favor of displaying data that the font doesn't contain.

**Comment by josh-hadley** [comment]
OK so we're down to either:
 - don't implement this request and continue to error (fail) when the input UFO doesn't contain `postscriptFontName`
 - patch the input UFO (either on the actual input or on a temp file that actually gets handed off to `tx`, AND with a warning to the user that this patching is occurring)

I'm fine with either one; doing nothing (not implementing) is easiest, of course although now that I've put the energy into this I'd like to see _something_ through.

**Comment by miguelsousa** [comment]
My vote goes to making `postscriptFontName` a requirement. It's a fundamental string to have in the final font, so enforcing it at the outset to anyone using the tools is the right approach IMO.

**Comment by cjchapman** [comment]
I think there's another option, which is to start with what Josh has in his local branch, add a flag indicating that the font name is synthesized, and then use it to output something like:
```
$ tx -dump -0 nopsfontname.ufo
...
FontName            "FamilyName-Regular" (synthesized)
```

**Comment by miguelsousa** [comment]
Let's go with that. I still think that it may come back to bite us tho.
Also, I disagree with seeing tx treat UFOs differently from other other formats it supports.

**Comment by frankrolf** [comment]
The big difference between UFO and other formats supported by `tx` is that UFO is a source format.
Users of `makeotf` don’t necessarily know that `tx` is working behind the scenes – therefore also don’t know why the PS font name is so important.

I can understand the hard stance “PS Font Name is required”, but I’d also want to emphasize that new users of the AFDKO often trip over this issue – simply because UI font editors generate the postscriptFontName themselves, and only put familyName/styleName at the forefront. In other words – the whole concept of postscriptFontName might not be know to the user.

This bug clearly is not critical, but I think a fix would make the FDK a bit more user-friendly.

**Comment by miguelsousa** [comment]
Frank, you know as well as I do how apps and systems rely on the PostscriptName to identify and to keep track of a font. You also know that the PostscriptName string has limit and composition constraints.

Synthesizing this string may work just fine in most cases. But what if the concatenation of FamilyName and StyleName yields a PostscriptName that is too long? What if FamilyName or StyleName contain spaces or non-ASCII characters? In these and likely other cases the developers sooner or later will be hit with problems that they won't know what their cause is.

As much as I understand your use case, I'm a strong believer that by hiding away the need of having to deliberately set the PostscriptName we'll be doing a disservice to the people that want to learn how to make reliable fonts. They can remain oblivious that tool A or B is working behind the scenes. The PostscriptName is essential not so much because of tx, but because it's a core piece of data for when the font is later installed and used. And my viewpoint is that font developers should be very well aware of that.

**Comment by frankrolf** [comment]
Okay, we have a decision then! 😊
Thanks for the comments.
