### ISSUE TITLE
Unicode range in glyph class

### ISSUE THREAD

**Issue by dy** [adobe-type-tools/afdko#1297]
(sorry in advance for noob question)

Is there a way to define unicode range as glyph class?

```fea
lookup pairs {
  @latin_caps = [A-Z];
  @cyr_caps = [uni0410-uni042F];
  pos @latin_caps 0 [acutecomb gravecomb tildecomb] <0 365 0 0>;
} pairs;
```

This gives error on `@cyr_caps`.

**Comment by frankrolf** [comment]
You can define an ad-hoc class like this, but you’ll need to space the dash.
This has to do with outside pressure to enable hyphens in glyph names.

A corrected version of your lookup would look like this:
```
lookup pairs {
  @latin_caps = [A - Z];
  @cyr_caps = [uni0410 - uni042F];
  pos @latin_caps 0 [acutecomb gravecomb tildecomb] <0 365 0 0>;
} pairs;
```

things to consider:
- you can write the features in _either_ production names _or_ final names, but you cannot mix them
- you need to be really sure of your glyph order if you use ad-hoc ranges, because the `-` relies on it.

What is the `pos` line doing?
I would expect
`pos @latin_caps [acutecomb gravecomb tildecomb] <0 365 0 0>;`
to lift combining accents by 365 when they follow latin caps.

If you are working with combining marks, you should consider the mark feature instead:
https://github.com/adobe-type-tools/python-modules#markfeaturewriterpy

**Comment by dy** [comment]
Getting the same error with spaced dash:
```sh
makeotfexe [FATAL] <NotoSerif-Italic> Invalid glyph range [uni0410-uni042F] [C:\projects\fonts\Noto\diacritics.fea 3]
```
As if space around dash collapses, according to the output.

As for the pos command, I tried
> pos @latin_caps [acutecomb gravecomb tildecomb] <0 365 0 0>
And that shifts first character instead of the second:
![image](https://user-images.githubusercontent.com/300067/106957893-9445d000-6706-11eb-8695-c28017494a4a.png)

I need 
![image](https://user-images.githubusercontent.com/300067/106957937-a1fb5580-6706-11eb-8707-3d688f12f51a.png)

> `markFeatureWriter.py`
Does that automatically create cyrillic combinations marks as well? We specifically need these:
```
дхр̣тара̄шт̣ра ува̄ча
дхарма-кшетре куру-кшетре
самавета̄ йуйутсавах̣
ма̄мака̄х̣ па̄н̣д̣ава̄ш́ чаива
ким акурвата сан̃джайа
```

**Comment by frankrolf** [comment]
The glyph names you are referencing in the feature file need to exist as glyph names in the font source data.
Those glyph names may coincide with Unicode names, but they don’t have to.

The markFeatureWriter does not automatically create data for you – it just interprets data already in the font.
Expected data:
- a group COMBINING_MARKS, containing the zero-width combining glyphs
- anchors set up in the combining marks
- anchors set up in the base glyphs

The output is a mark feature file which can be used when building the font.
For an example, see Source Serif’s source files, e.g.:
https://github.com/adobe-fonts/source-serif/blob/main/Roman/Instances/Text/Regular/mark.fea

I think Source Serif does in fact support the string you suggest.
If you have a specific use case for combining marks below Cyrillic letters, please add it to the issue here: https://github.com/adobe-fonts/source-serif/issues/72#issuecomment-768195125

Thanks!

**Comment by frankrolf** [comment]
Thanks for explaining your thinking behind the `pos` command – that indeed is a good case for using the `mark` feature (which is also `pos`, but different lookup type – 4 instead of 2). In your example, the mark on top of B will look OK – but it won’t be centered on other, wider glyphs.

**Comment by dy** [comment]
> The glyph names you are referencing in the feature file need to exist as glyph names in the font source data.

In fact they do exist in font, I have to manually list all names, the script just doesn't read unicode range. Does it seem like a bug?

Yes, initially I started with GPOS type 4, but it took manual adjusting anchors for many characters ([ref](https://github.com/krishnized/fonts/blob/111fc9266769955dec83f8e7e2b35351b297ba2a/Noto/diacritics.fea)), I decided having generic combining mark offsets automatically cover many close-to-average glyphs (in mono-font - all), the code is more compact and possibly is the result.

**Comment by frankrolf** [comment]
While fonts do contain code points, they also contain lots of unencoded glyphs. The Unicode range approach makes sense from a user perspective, but ultimately is brittle. Some Unicode ranges are incomplete, contain deprecated characters, etc. 
I use glyph ranges only whenever I want to test something (e.g. `sub [A - Z] by [A.sc - Z.sc];`), and usually end up expanding those ranges to make them explicit.

**Comment by miguelsousa** [comment]
Glyph range expansion is a very limited feature, as explained by the [FEA specification](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#2.g.i). Perhaps that's what's blocking this use case.

**Comment by frankrolf** [comment]
Wow, alphabetical order! I did not even realize that.
I should warn anyone against using glyph ranges in features then! :-)

**Comment by dy** [comment]
Ok, I guess consider it unresolvable then.
