### ISSUE TITLE
[buildmasterotfs] ranges break in feature file 

### ISSUE THREAD

**Issue by dy** [adobe-type-tools/afdko#1307]
If feature file in one of masters has range definition as
```fea
@value = [_0-_9];
```
The `buildmasterotfs` throws error:

```sh
makeotfexe [ERROR] <Wavefont> Glyph "" not in font. [C:\projects\wavefont\masters\1_0.ufo\features.fea 3]
```

Enumerating all characters manually fixes the issue, but `fontmake` doesn't have that issue.

**Comment by frankrolf** [comment]
I came across this by accident, commenting anyway:
A range needs to be written out with a space around the dashes.
Apart from the

**Comment by dy** [comment]
[wavefont](https://github.com/dy/wavefont) has glyphs from `_0` to `_127`, mapped to different characters.

For `@value = [_0 - _127] fontmake still throws an error: 
```
fontmake: Error: In 'sources/Wavefont.designspace': Generating fonts from Designspace failed: /Users/div/projects/wavefont/sources/Wavefont-wmin,rmin,amin.ufo/features.fea:12:11: Bad range: "_0" and "_127" should have the same length
```
But you're right, values like `[_0 - _9 _10 - _99 _100 - _127]` work well

**Comment by frankrolf** [comment]
Thanks for closing this!

For whoever reads this – ranges are extremely brittle, since they are ordered alphabetically. That also explains why your “split by digits” example works.

This isn’t a hard rule, but an underscore usually indicates a ligature, such as `f_f_i`. To make things more predictable, I suggest naming your glyphs `wave000` – `wave127` – but of course that’s up to you :-)
