### ISSUE TITLE
interpreting psstemhist reports

### ISSUE THREAD

**Issue by tkacvins** [adobe-type-tools/afdko#1444]
HI,

I am looking into `psstemhist` output, and I am not quite sure how to decipher the reports generated by it for starting to hint a font in FontLab (for instance).  Are these values to be used in these arrays (which I gleaned from the font on which I ran `psstemhist`)?

```
/BlueValues [-11 0 444 453 655 676 686 697] ND
/OtherBlues [-201 -194] ND
/StdHW [47] ND
/StdVW [114] ND
/StemSnapH [40 47] ND
/StemSnapV [114 142] ND
```

**Comment by frankrolf** [comment]
The values you see here (presumably from a OT font’s CFF table or T1 font’s topDict) are

- alignment zone values (incl. baseline zone)
- bottom alignment zone values
- default horizontal stem
- default vertical stem
- all horizontal stems
- all vertical stems

The existence of these values implies that this font has already been hinted, or was at least prepared for hinting.
Generally, these values are added to a font by the designer, and a subset is required in order to hint a font with `psautohint`.

`psstemhist` has two modes:
### find common stem values (for defining `StemSnapV`/`StemSnapH`, possibly additional stems)
```
psstemhist -g -a A-Z,a-z font.ufo
```
this command will output two text files (.hstm.txt/.vstm.txt), which list possible stem values, in order of appearance

### find vertical extrema (useful for defining `BlueValues`/`OtherBlues`)
```
psstemhist -z -a -g A-Z,a-z font.ufo
```
this command will output two text files (.top.txt/.bot.txt), which list the relevant glyph extrema.

In each of the commands above, the glyph set is limited (`-g`) to a subset of default glyphs, so the stem results are not skewed in favor of a glyph with many accented variants. `-a` will make sure also curved stems are included in the analysis.


While many modern font editors allow for automated glyph analysis for filling in these values, the slow approach `psstemhist` takes can be valuable to analyze if glyphs have gone out of alignment.

Please feel free to re-open this issue if your question is not answered completely.
