### ISSUE TITLE
makeotf: "[Warning] the feature file does not contain a 'vert' feature"

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#148]
If the `vert` feature is written with the exception of "main feature file" by calling include command, makeotf will prompt "[Warning] the feature file does not contain a 'vert' feature"

**Comment by kenlunde** [comment]
I can confirm that this is a (benign, because the resulting font includes a well-formed 'vert' GSUB feature) _makeotf_ bug, and can be confirmed when building [Source Han Code JP](https://github.com/adobe-fonts/source-han-code-jp), which uses the "include" statement to import the 'vert' GSUB feature definition.

**Comment by LiXiangchen** [comment]
Yes, It does not affect the resulting font, just a prompt bug.
