### ISSUE TITLE
[tx] Add iFD to glyphs mappings to groups.plist

### ISSUE THREAD

**Issue by kaydeearts** [adobe-type-tools/afdko#1539]
Within groups.plist for CID-keyed UFO, add a dictionary of iFDs that point to a list of glyphs to identify which glyphs use which fdicts within the FDArray

**Comment by punchcutter** [comment]
I updated the test file tests/tx_data/input/cid_roundtrip/testCID.ufo with the new setup for FDArraySelect groups in groups.plist. Removed PrivateDicts from the FDArrays in lib.plist and moved the data in them to the top level. Also changed `com.adobe.type.postscriptCIDMap` to only map glyph names to CID instead of having iFD in there as well.

**Comment by kaydeearts** [comment]
Implemented in #1576 . Here's an example of [what the groups.plist should look like!](https://github.com/adobe-type-tools/afdko/blob/develop/tests/tx_data/input/cid_roundtrip/testCID.ufo/groups.plist)
