### ISSUE TITLE
proofpdf test_round_glyph_bounds_values_bug128[ttf] failing with fonttools 4.37.2

### ISSUE THREAD

**Issue by skef** [adobe-type-tools/afdko#1560]
Seems like the values being read from the ttf are off by 5 horizontally compared with the reference pdf.

generated: [bug128ttf.pdf](https://github.com/adobe-type-tools/afdko/files/9595181/bug128ttf.pdf)

reference: [bug128_ttf.pdf](https://github.com/adobe-type-tools/afdko/files/9595184/bug128_ttf.pdf)

**Comment by josh-hadley** [comment]
In tracking down the cause of this test failure, I noticed a change in fontTools from 4.37.1 -> 4.37.2 which likely has something to do with the difference.

In [the commit prior to what went into 4.37.2](https://github.com/fonttools/fonttools/blob/c04afbedafb58fbf74cbb30cae7c1c6a462541f6/Lib/fontTools/ttLib/ttGlyphSet.py#L105), `_TTGlyphGlyf.draw()` calls `glyph.draw` as:
```
glyph.draw(pen, glyfTable, offset)
```

But in the commit that went into [4.37.2](https://github.com/fonttools/fonttools/blob/b818e1494ff2bfb7f0cd71d827ba97578c919303/Lib/fontTools/ttLib/ttGlyphSet.py#L116) it's calling it as:
```
glyph.draw(pen, offset)
```

i.e. it's dropped the `glyfTable` arg

The signature for `glyph.draw` is `(self, pen, glyfTable, offset=0)` and if I place a breakpoint and step into `glyph.draw` with our test case under fonttools 4.37.2, the `glyfTable` object is "5" and `offset` is 0 which seems like 🐛 . Under 4.37.1, `glyfTable` is a glyf table object and offset is more like what I'd expect.

@anthrotype @justvanrossum was that change intentional?

**Comment by justvanrossum** [comment]
It's a bug, which oddly doesn't crash. I'll make a PR to fix it right now.

**Comment by justvanrossum** [comment]
I'm quite confident that this PR fixes it:
- https://github.com/fonttools/fonttools/pull/2825

**Comment by anthrotype** [comment]
FYI https://github.com/fonttools/fonttools/releases/tag/4.37.3
