### ISSUE TITLE
building fails on manjaro

### ISSUE THREAD

**Issue by Shoxx98** [adobe-type-tools/afdko#1736]
[build log.txt](https://github.com/adobe-type-tools/afdko/files/14272973/build.log.txt)
[inxi.txt](https://github.com/adobe-type-tools/afdko/files/14272974/inxi.txt)
see files attached on system used and the log in detail

**Comment by skef** [comment]
Based on the error, try installing `pkgconf` (or verifying that it is installed). As in `pacman -S pkgconf`. 

Because `afdko` is a python package it can be tricky to express these sorts of dependencies internally, but so far we've found that systems that tend to have compiliers installed also usually have `pkg-config` installed.

**Comment by Shoxx98** [comment]
apparently not an issue that normally needs fixing
