### ISSUE TITLE
A .designspace document produced by fontmake is not accepted by AFDKO’s makeInstancesUFO 

### ISSUE THREAD

**Issue by MrBrezina** [adobe-type-tools/afdko#179]
A .designspace document generated from .glyphs source using fontmake is refused by makeInstancesUFO as it does not include `postscriptFontName` attribute for each instance. As @anthrotype noted: this should be optional, at least according to https://github.com/LettError/designSpaceDocument

Perhaps AFDKO could infer the `postscriptFontName` from other attributes if this is not provided? It would be nice if AFDKO and fontmake played well together by default.

Maybe new AFDKO does not have a problem with that, I have not tried that yet.

See also https://github.com/googlei18n/fontmake/issues/306

**Comment by anthrotype** [comment]
glyphsLib always writes `familyname` and `stylename` attributes for instance elements. It writes the `postscriptfontname ` only when user provides a custom parameter to use a PostScript name different from the default one which could be derived from the above two.
makeInstanceUFO could first attempt to find `postscriptfontname`, and if that's missing try with the `familyname` and `stylename` combo.

**Comment by miguelsousa** [comment]
Since `postscriptfontname` is optional for MutatorMath, I agree that **makeInstancesUFO** shouldn't fail if that attribute is missing.

I don't like the idea of having makeInstancesUFO assemble `postscriptfontname`. The tool that consumes the UFOs should do that, or enforce the presence of [`postscriptFontName`](http://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#postscript-specific-data).
