### ISSUE TITLE
FDK produces broken font in Windows when AGL and GOADB conflicts

### ISSUE THREAD

**Issue by benkiel** [adobe-type-tools/afdko#188]
If one assigns a unicode value to a glyph when there is another glyph in the font gets that unicode same value from the AGL, the resulting font will install and work in OS X, but Windows will refuse to install the font.

Round-tripping the font through fontTools will fix the font to be installable in Windows.

It appears, via FontValidator, that the cmap produced has the endCode array not in ascending order, at least that's the error that is given by FontValidator.

I don't know if this is actually a bug or not — but if the FDK encounters this, at least a warning should be thrown, if not a refusal to compile the font if this behavior isn't considered a bug.

**Comment by readroberts** [comment]
This is indeed a bug in the FDK. There used to be a check for this case, that issued a fatal error if two glyphs were mapped to the same Unicode value. This produces a bad MS platform Unicode cmap subtable, hence the failure to install under Windows. This is fixed by restoring the check, with commit 73486ce72cf8611a4d9baeff17b1505fc61dfad5.
