### ISSUE TITLE
Dead and missing links on the Adobe website

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#194]
There is no download link to the latest releases on the [Adobe AFDKO website](http://www.adobe.com/devnet/opentype/afdko.html) anymore. In the past there were links to the releases stored on the Adobe servers. I would link to the release section of the AFDKO repository instead or additionally.

And please check [the links to the font related documents.](http://www.adobe.com/devnet/opentype/archives.html) They don't work anymore (redirection to www.adobe.io).

And the links to the PDF on http://www.adobe.com/devnet/font.html are also redirected to nowhere.

(Many of these old documents are still useful.)

**Comment by readroberts** [comment]
This is unintended. Thanks for reporting this problem. Looks like someone in the Adobe did a major redesign of the Adobe web look, and messed up the AFDKO pages in the process. I will get this fixed.

- Read

**Comment by readroberts** [comment]
Hi Arno; I finally got the tools set up so that I could fix the missing download link. Can you check the other two links again?  When I click on the links in your note above, I get to the right pages, http://www.adobe.com/devnet/opentype/archives.html and http://www.adobe.com/devnet/font.html.

**Comment by Arno-Enslin** [comment]
Sure. But let me ask anothetr question first: I had sent you a mail regarding to the mssipotf.dll 64 bit version a week ago. Did you receive it?

--------------------------------------------------

Except from the following the links on "http://www.adobe.com/devnet/font.html" work:

**Specifications**
https://www.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5902.AdobePSNameGeneration.html

**CJK /CID-keyed fonts**
The "CMap Resources open source project at Open @ Adobe" is not available on "http://sourceforge.net/adobe/cmap/" anymore, but on "https://github.com/adobe-type-tools/cmap-resources/".

**PDF core font information**
_Font Metrics for PDF Core 14 Fonts_
http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/Core14_AFMs.sit.hqx
http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/Core14_AFMs.zip
http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/Core14_AFMs.tar

_CMaps for PDF CJK Fonts_
http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/chinese_t.zip
http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/japanese.zip
http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/korean.zip

-----------------------------------------------------------------------

All links on http://www.adobe.com/devnet/opentype/archives.html are still redirected to https://www.adobe.io/.

**Comment by kenlunde** [comment]
Parts of this page seem to have been reverted, because I distinctly remember having the link to the "CMap Resources" project changed to point to GitHub. About the _CMaps for PDF CJK Fonts_, it's probably best to simply point to the [Mapping Resources for PDF](https://github.com/adobe-type-tools/mapping-resources-pdf) project on GitHub.

While we're touching that page, the ones for _Adobe-Japan1-6_, _Adobe-GB1-5_, and _Adobe-CNS1-6_ (which is now Adobe-CNS1-7) can now point to their versions on GitHub: [Adobe-Japan1](https://github.com/adobe-type-tools/Adobe-Japan1/), [Adobe-GB1](https://github.com/adobe-type-tools/Adobe-GB1/), and [Adobe-CNS1](https://github.com/adobe-type-tools/Adobe-CNS1/).

I cannot help with the dead links in _Font Metrics for PDF Core 14 Fonts_.

**Comment by readroberts** [comment]
Thanks, I am aware of some the dead links, but not all.  It just takes a little longer to fix these. The two pages I restored were just missing the links on the page; the target resources were still present on the servers. With these others, I need to find or re-create the original pages and data.

**Comment by miguelsousa** [comment]
@cjchapman please check if this issue can be closed. Thanks!

**Comment by cjchapman** [comment]
# status

## active pages
These pages have been updated so that the links on these pages now point to live PDFs, GitHub repos, etc.:
* www.adobe.com/devnet/font.html
* www.adobe.com/devnet/opentype.html
* www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html
* www.adobe.com/products/type.html

## deactivated pages
These pages have been deactivated and are no longer be reachable:
* www.adobe.com/devnet/opentype/afdko.html
* www.adobe.com/devnet/opentype/afdko/eula.html
* www.adobe.com/devnet/opentype/archives.html
* www.adobe.com/devnet/opentype/gdk.html
