### ISSUE TITLE
[CheckOutlinesUFO.py] filterGlyphList creates set, not list

### ISSUE THREAD

**Issue by robinsdg** [adobe-type-tools/afdko#225]
This function creates an issue where the entire script fails as it cannot `sort` a `set`. The `UFO` file produces no errors after I add `glyphList = list(glyphList)` after the declaration, but it doesn’t seem like that should be the fix. Is there something wrong with my source files, or my installation, or is it something else?

**Comment by cjchapman** [comment]
There was a bug that is fixed in the latest code on the master branch, but not yet released. The new code has this line:
```python
    glyph_list = filter_glyph_list(
        options, defcon_font.glyphOrder, options.file_path)
```
Note that the name changed from `filterGlyphList` to `filter_glyph_list` as part of our move towards PEP 8 compliance. The important thing here is that we're now using `defcon_font.glyphOrder` instead of `defcon_font.keys()`.

Here's the specific commit that fixes the bug:
https://github.com/adobe-type-tools/afdko/pull/219/commits/4f6007fd17cea58ca322a32d34479af676bec68c

**Comment by robinsdg** [comment]
Thanks, Christopher!

**Comment by cjchapman** [comment]
You're welcome, Robin. 

Shall we close this issue now?
