### ISSUE TITLE
Question about com.adobe.type.autohint in UFO

### ISSUE THREAD

**Issue by twardoch** [adobe-type-tools/afdko#25]
Adobe's storage format for PS hints in the GLIF lib is as follows: 
```xml
<lib>
 <dict>
 <key>com.adobe.type.autohint</key>
 <data>
 <hintSetList>
   <hintset pointTag="ab02">
     <hstem pos="-14" width="211" />
     <hstem pos="455" width="180" />
     <hstem pos="856" width="211" />
     <vstem pos="74" width="336" />
     <vstem pos="819" width="336" />
   </hintset>
   <hintset pointTag="hr02">
     <hstem pos="21" width="-21" />
     <hstem pos="455" width="180" />
     <hstem pos="739" width="328" />
     <vstem pos="74" width="336" />
     <vstem pos="850" width="305" />
   </hintset>
 </hintSetList>
 </data>
 </dict>
 </lib>
```

but in light of the discussion on the ufo-spec list ( https://groups.google.com/d/topic/ufo-spec/yZ8CrPWoAI4/discussion ), the contents of the <data> element inside the lib must be base64-encoded, so the above code should look like this: 

```xml
<lib>
 <dict>
 <key>com.adobe.type.autohint</key>
 <data>
 ICA8aGludFNldExpc3Q+CiAgICA8aGludHNldCBwb2ludFRhZz0iYWIwMi
 I+CiAgICAgIDxoc3RlbSBwb3M9Ii0xNCIgd2lkdGg9IjIxMSIgLz4KICAg
 ICAgPGhzdGVtIHBvcz0iNDU1IiB3aWR0aD0iMTgwIiAvPgogICAgICA8aH
 N0ZW0gcG9zPSI4NTYiIHdpZHRoPSIyMTEiIC8+CiAgICAgIDx2c3RlbSBw
 b3M9Ijc0IiB3aWR0aD0iMzM2IiAvPgogICAgICA8dnN0ZW0gcG9zPSI4MT
 kiIHdpZHRoPSIzMzYiIC8+CiAgICA8L2hpbnRzZXQ+CiAgICA8aGludHNl
 dCBwb2ludFRhZz0iaHIwMiI+CiAgICAgIDxoc3RlbSBwb3M9IjIxIiB3aW
 R0aD0iLTIxIiAvPgogICAgICA8aHN0ZW0gcG9zPSI0NTUiIHdpZHRoPSIx
 ODAiIC8+CiAgICAgIDxoc3RlbSBwb3M9IjczOSIgd2lkdGg9IjMyOCIgLz
 4KICAgICAgPHZzdGVtIHBvcz0iNzQiIHdpZHRoPSIzMzYiIC8+CiAgICAg
 IDx2c3RlbSBwb3M9Ijg1MCIgd2lkdGg9IjMwNSIgLz4KICAgIDwvaGludH
 NldD4KICA8L2hpbnRTZXRMaXN0Pgo=
 </data>
 </dict>
 </lib>
```

At FontLab, we have a similar problem, so at this point we've introduced a switch when writing UFO, to either write it in the invalid, human-readable form (1st example) or in the valid, base64-encoded form (2nd example). 

Do you know if AFDKO is "ready" to support (read) the base64-encoded variant? Also, are there plans to switch to the valid form when writing it? 

Thanks,
Adam

**Comment by davelab6** [comment]
@readroberts any progress with the plist-compliant version of this? Seems like UFOv4 is still some time away.

**Comment by sansplomb** [comment]
Also looking forward to any progress on this issue. 
I think the alternative Adam is proposing is very sensible: it seems best to avoid <data>.

**Comment by typesupply** [comment]
The ball is more in my court than Read's at this point. It is on my list to standardize and backwards port it to UFO 3. The hint data will be stored in the lib under a public key, rather than being a full part of GLIF. I'm hoping to get to it in the next few weeks. (My day job is very busy right now.) For more info on why this isn't easy, there is a long discussion about TTF hints in my Robothon presentation from last week. It should be [online in the future](https://twitter.com/robothonconf/status/574678238930288640).

The discussion about this will all take place on the [UFO Specification mailing list](https://groups.google.com/forum/#!forum/ufo-spec).

**Comment by sansplomb** [comment]
Looking forward to see this as official specification so that we can all easily align.

However I think adam's suggestion of XML plist compliant glif lib is good, although it may eventually be a bit space-consuming...

And since there is no standard Visual TrueType hinting, I think the definition of hint data stored in the UFO's lib.plist should be flexible and open, so that various types of visual commands could be stored there, including new ones that do not yet exist.

**Comment by readroberts** [comment]
I am waiting on the new specification before I do any work on the FDK. I also like Adam's approach to making the data be plist compliant, but will be happy to follow whatever goes in the spec. The current Type1 hint is very much T1 specific - it would be good to have common syntax for the elements that are common between T1 and TT - there are some!

**Comment by nlsp** [comment]
@readroberts @twardoch for the “superbly readable plist XML” … i came across the same problem without having watched this thread and ended up converting to a slightly different format:
```xml
  <key>com.fontfabrik.hintsets</key>
  <array>
    <dict>
      <key>pointTag</key>
      <string>hr00</string>
      <key>stems</key>
      <array>
        <string>hstem 0 -21</string>
        <string>hstem 350 26</string>
        <string>vstem3 46 40 188 40 330 40</string>
      </array>
    </dict>
  </array>
```
Since everything under `elements` or `stems` is postscript specific it doesn’t matter much code-wise whether all attributes are encoded verbosely in xml or simply written as a simple postscript-like string, and it makes for an even more human readable glif structure.

:-)

**Comment by twardoch** [comment]
That's actually pretty good. Given it's under consideration to use VTTalk for storing high-level TT hinting — VTTalk would most likely look quite similar, since it's also "plain text", which can be logically converted into an array of strings, one per line. And TT assembly hinting also could follow this. Very good!

**Comment by nlsp** [comment]
Thanks so much for support, but even in the postscript hintset case this is semantically incomplete: the given pointTag labels depend on contour order and their respective starting points.

When anything changes, the label will survive but the hint replacement will have to be regenerated, most likely resulting in different hint sets and pointTag labels to become valid again. And the information needed to do so isn’t encoded in the autohinter output. ‘Links’ would be more useful than raw hint positions and widths.

For higher level hinting commands as in VTTtalk we would like to see point tag references to source point indices and to target points that become touched (in horizontal or vertical direction), and the ascii strings that make up the actual command then need to be marked to make clear which arguments are indices… possible but not simple. And perhaps better suited to a less generic representation…

**Comment by davelab6** [comment]
@readroberts is the new spec out?

**Comment by readroberts** [comment]
I am going ahead and revising the AFDKO private T1 hint format to  a plist-compatible format. I very much like the proposal above from nlsp on April 1st, and am pretty much adopting that. The first pass of this is now checked in under the AFDKO Open Source site, and full build will be coming to the Adobe download site in a week or two.  As before, I consider this a temporary format, and will switch over to whatever the UFO spec developers work out, when that happens.  The format is documented as _hintFormat2_  in FDK/Tools/SharedData/FDKScripts/ufoTools.py. It looks like:
			<key><com.adobe.type.autohint></key>
    		<dict>
				<key>id</key>
				<string> <fingerprint for glyph> </string>
				<key>hintSetList</key>
				<array>
					<dict>
						<key>pointTag</key>
						<string> <point name> </string>
						<key>stems</key>
						<array>
							<string>hstem <position value> <width value></string>*
							<string>vstem <position value> <width value></string>*
							<string>hstem3 <position value 0>...<position value 5></string>*
							<string>vstem3 <position value 0>...<position value 5></string>*
						</array>
					</dict>*
				</array>

				<key>flexList</key>*
				<array>
					<string><point name></string>+
				</array>
			</dict>

**Comment by readroberts** [comment]
No complaints or comments in several months! Closing.

**Comment by schriftgestalt** [comment]
I just checked the Source Sans repo. It still uses the incompatible format. This leads to a lot of data loss if the file should be processed by a standard compiling parser, as it has to skip everything. 

Can we just agree on a spec to store the PS hints as first class elements next to the contours in the glif? There we can use the syntax as is because it can be plain XML, without the requirements of plist.

**Comment by anthrotype** [comment]
yes please!

**Comment by typesupply** [comment]
I would much, much, much rather have the existing plist data structure move to the lib under a key with a name like com.adobe.postscript.hints. If Adobe wants this format to be universal, I'd be completely happy to make it an official part of the UFO spec and let it live in public.postscript.hints.

I prefer this over first class elements simply for the sake of pragmatism. If this moves to the lib, it can be an official, published part of the spec before the weekend. Someone just needs to submit the text in a PR for the UFO spec. Additionally, this will work with every existing UFO reader/writer right away because of the way the lib is specified. First class elements are going to take a lot longer to specify and even longer to implement. Several people, myself included, have started to write first class elements, but it's a HUGE project that requires deep knowledge and, well, everyone is busy.

I mean, if someone were to say, "Hey, here's a spec for a full set of first class elements for PS and TT hints, a patch for the example implementation, a bunch of test cases and, by the way I'm totally an expert on this so this doesn't need review!!!" I'd gladly take it. But, short of that, I'm also cool with taking what already exists and moving it to the right place. :)

(It's been at least ten decades since I reviewed Adobe's format, so I have no idea what it looks like now. But, I remember that the method for referencing points was a concern. We could work that out on the UFO list if it is still an issue.)

**Comment by twardoch** [comment]
I wouldn't want to change the core GLIF structure. It means that changing the hinting would change the main structure of the GLIF, and would break compatibility. If we'd ever want GLIF2, then yeah, but then we should think about other things as well rather than just adding PS hints.

**Comment by readroberts** [comment]
In the long run, I would much rather see a unified syntax for TrueType and PostScript hinting added to the GLIF spec, but I second Tal in that it is a lot of work, and I don't know how to do the unified syntax part - the formats are very different. For the short term, I strongly support Tal's proposal, and am happy to jump start this by submitting a PR for some documentation for public.postscript.hints. For the record I happened to have implemented a first pass implementation of this, but I don't consider it to be an Adobe spec - several people contributed to it, and this was after the AFDKO was OpenSource'd.

 I just submitted PR "Add documentation for public.postscript.hints #53" to unified-font-object/ufo-spec.
