### ISSUE TITLE
question about glyph printing into PDF with transparency.

### ISSUE THREAD

**Issue by nanife** [adobe-type-tools/afdko#26]
I want to publish a PDF with glyph comparison cells among several fonts. In it, each grid cell has compared glyphs, a glyph on top of another glyph(s).
is there a possible way to draw glyphs into PDF with transparency like below?

in this example, red colored glyph is on top of blue colored glyph.
![glyphcomparison](https://cloud.githubusercontent.com/assets/10296213/5554057/00c9a196-8c81-11e4-8115-6c7747ba1497.jpg)

In reportlab, it is possible to draw glyphs and fill its color with 'alpha=x.x' value like this.
colorValue = Color(0, 0, 100, alpha = 0.5)

But, in fontPDF module, I just found like this.

Color values are set as a triplet of (Red, Green, Blue) values between 0 (dark)
and 1.0 (light). Examples:
(1.0,0,0) is red
(1.0, 1.0, 1.0) is white

If I should add transparency, to which module should I do?

Thanks in advance

**Comment by readroberts** [comment]
I chose to use the  pdfdoc.py/pdfgen.py modules because a) they were open source and b) were very simple, implementing only a subset of PDF version 1.2. Extending these modules should be pretty simple.  You will need to edit pdfdoc.py::SaveToFileObject to declare the file to be a PDF version that supports transparency (1.4  or later), and then add some code in pdfgen.py to define a new function  to set opacity (ca or CA) for the current graphics state.

**Comment by nanife** [comment]
Thanks for your comment!
I'll look into those modules and I'll try it on. Thanks again!
