### ISSUE TITLE
dead code in cswrite.c (autohintlib/ac)

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/afdko#29]
There is a lot code like this:

```
#if DEBUG
            sws("10 div");
#else
            sws("10 div");
            /* WRTNUM(10); OUT(ESC); OUT(DIV); */
#endif
```

Can someone explain the commented code? Can it be removed?

**Comment by readroberts** [comment]
I am sure that the code can be removed. The autohint code has not had anything beyond point fixes since about 1992, so there is no one who can report original intent anymore.  However, I looked at all DEBUG macros, and there is no difference between the effect of DEBUG=1 and DEBUG = 0. I think it is also pretty clear that there was an original branch with only the code that is still present, but which now commented out in the (DEBUG==0) branch. The next step was adding the code which is now in the DEBUG==1 branch. The final step was commenting out the original code in the (DEBUG==0) branch, and adding the same code as in the (DEBUG==1) branch. I speculate that the developer chose to keep the two branches and the commented out code in order to make it easier to revert to the original code if some problem showed up, but never bothered to do the final clean up.  I suspect that source code control in 1986-1991 was pretty basic and it may not have been not easy to switch between versions.

**Comment by miguelsousa** [comment]
I believe this has been fixed. The current version of `cswrite.c` doesn't have those lines.
