### ISSUE TITLE
Remove clean_afdko and check_afdko methods

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#336]
First confirm that they're no longer needed.

**Comment by readroberts** [comment]
@miguelsousa I can confirm that they are not needed. I added these two functions when I was first starting to package the afkdo. I needed them then because 'python setup.py clean' does not remove  script tools. However, 'pip uninstall' does.

**Comment by anthrotype** [comment]
The `setup.py clean` command is the equivalent of `make clean`, or the reverse of `setup.py build`. It simply removes the build artifacts (usually inside the `build` subfolder), does not uninstall anything.

Actually, I see that the current afdko build process (the BuildAll.sh and similar shell scripts) leave the built binaries in the source tree, rather than compiling them in a separate build folder. To force rebuilding, I sometimes do `git clean` to remove the all built files that are not in version control.
Maybe a custom `setup.py clean` command that removes all the compiled files could be handy. Of course, this is entirely different thing from `pip uninstall`.

**Comment by miguelsousa** [comment]
Started working on this.
