### ISSUE TITLE
Licensing clarifications in headers

### ISSUE THREAD

**Issue by n7s** [adobe-type-tools/afdko#4]
Can you please clarify that various cmaps are under 3-clause BSD and some FontLab macros are under MIT in LICENSE.txt at the root of the project? 

Also, many files still have the following restricted license information in their headers:

"Patents Pending                                              
                                                                       
NOTICE: All information contained herein is the property of Adobe     
Systems Incorporated. Many of the intellectual and technical          
concepts contained herein are proprietary to Adobe, are protected     
as trade secrets, and are made available only to Adobe licensees      
for their internal use. Any reproduction or dissemination of this     
software is strictly forbidden unless prior written permission is     
obtained from Adobe. "  

which is probably not your intent, can they please be removed? 

Thanks.

**Comment by davelab6** [comment]
@readroberts any update on this? :)

**Comment by readroberts** [comment]
Is there a reason that the current license for the Adobe CMAP files is a problem, other than consistency with the AFDKO Apache 2.0 license? Since the Adobe CMAP files are published as OpenSource elsewhere, I currently think the best solution is to simply remove the Adobe CMAP files from the AFDKO, and simply reference the SourceForge site.

**Comment by davelab6** [comment]
> the best solution is to simply remove the Adobe CMAP files from the AFDKO, and simply reference the SourceForge site

If you set up something like https://github.com/adobe-type-tools/cmaps then you can use git submodules to include them in this repo

**Comment by chemoelectric** [comment]
Don’t do that; it’s far too complex and weird. KISS.

I’d probably copy the free software CMAP files, since it is no disaster if one happens to fall (perhaps temporarily) out of sync with some separate project, in a thing like this; and that way you are dependent on no one for a complete system.

**Comment by kenlunde** [comment]
I plan to eventually move the "CMap Resources" project from SourceForge to GitHub, and given that there is some amount of work involved in doing that, it represents an opportunity to change the existing open source license, which was crafted by our Legal in mid-2009, to Apache 2.0. I have accelerated the internal discussions about this particular point, and have suggested that the following be used in the CMap resource headers:
~~~
  %%Copyright: Copyright 1990-2015 Adobe Systems Incorporated
  %%Copyright:
  %%Copyright: Licensed under the Apache License, Version 2.0 (the
  %%Copyright: "License"); you may not use this file except in
  %%Copyright: compliance with the License. You may obtain a copy of
  %%Copyright: the License at
  %%Copyright: http://www.apache.org/licenses/LICENSE-2.0.html
  %%Copyright:
  %%Copyright: Unless required by applicable law or agreed to in
  %%Copyright: writing, software distributed under the License is
  %%Copyright: distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  %%Copyright: CONDITIONS OF ANY KIND, either express or implied. See
  %%Copyright: the License for the specific language governing
  %%Copyright: permissions and limitations under the License.
~~~
Also, keep in mind that the CMap resources that are included in the "CMap Resources" project, some of which are included in AFDKO, are the public ones that are based on static glyph sets, and don't change very often. Changes are triggered by new Supplements, and sometimes by new versions of Unicode (a previously unencoded glyph may now be encoded). The CMap resources that are used by fonts based Adobe-Identity-0 ROS, such as Source Han Sans and Noto Sans CJK, are different, because they are closely bound to the font itself. (With that said, the UTF-32 CMap resources for Source Han Sans and Noto Sans CJK would also be changed in the Version 1.002 update to reflect the open source license change.)

**Comment by kenlunde** [comment]
Just FYI, the "CMap Resources" project is available on [GitHub](https://github.com/adobe-type-tools/cmap-resources) as of today, and the headers of each CMap resource now specify the Apache License, Version 2.0. The project on SourceForge shall be decommissioned on 2015-06-01.

**Comment by davelab6** [comment]
Thanks Ken!!

**Comment by kenlunde** [comment]
Note that only a very small number of the CMap resources should be included in AFDKO, specifically the legacy Macintosh ones (*83pv-RKSJ-H*, *KSCpc-EUC-H*, *B5pc-H*, and *GBpc-EUC-H*) and the UTF-32 ones. These are the only ones that are useful for OpenType/CFF font development purposes.
