### ISSUE TITLE
setsnapl.pl -o results vary hugely

### ISSUE THREAD

**Issue by weiweihuanghuang** [adobe-type-tools/afdko#42]
`perl setsnap.pl -o -l36 -u128 -r72  < font.otf.hstm.txt`
A hairline weight and the result is:
[16] 156 30

What is the secondary value (156) and tertiary value (30) for? Are they measuring the wrong direction, i.e. the counters?

**Comment by kenlunde** [comment]
This more of an artifact of the stemHist tool, which generates the input file for the setsnap.pl script. The first values that it generates, which are in brackets, are generally the better ones, and the other values turn up because they fall within the parameters.

Keep in mind that setting hinting parameters is part science and part art. A good default, which generally gives good results, is to simply select the highest-frequency stem value.
