### ISSUE TITLE
Strikeout/Underline

### ISSUE THREAD

**Issue by YoannM** [adobe-type-tools/afdko#47]
I report a problem with strikeout and underline, noticed by Jens K. on robofont forum.
I have the same problem.

"I noticed that the values in RFont.info.openTypeOS2StrikeoutSize and RFont.info.openTypeOS2StrikeoutPosition are not written into a generated OTF. Instead, the openTypeOS2StrikeoutSize is always the same as the postscriptUnderlineThickness and the openTypeOS2StrikeoutPosition is set to the x-height * 0.6, it looks like some kind of FDK fallback is taking place there."

**Comment by readroberts** [comment]
This is due to a bug in the 'tx' program, which does not use these fields from the UFO fontinfo.plist file. Easy to fix: uforead.c:setFontDictKey() needs two more if-else cases. Will fix this when I next get back to working on the FDK, in a few weeks. The only work-around is to patch these values in the final OTF, wit a tool like ttx.

**Comment by readroberts** [comment]
On looking to this, I think it not appropriate to change current behavior. The real issue is that 'tx' operates on only Type1/Type 2 related information. It is not a OpenType reader/writer: it is a Type1/Type2/CFF font reader/writer.  It happens to work with OpenType fonts as input, but reads only the table, and can output only info from the CFF table.  The UFO font format contains a lot of meta data which is outside the set of data contained in a Type1/Type2 font - and is in fact, a superset of the OpenType data. I coudl certainly add support to carry through the fields openTypeOS2StrikeoutSize/ openTypeOS2StrikeoutPosition from a UFO font as input, but that really doesn't make sense all by itself - if we take 'tx' down this path, it should pass through all the meta data for both UFO and OTF, whcih is really outside its scope

**Comment by typemytype** [comment]
thanks for clarifying
