### ISSUE TITLE
`makeotf` error

### ISSUE THREAD

**Issue by pathumego** [adobe-type-tools/afdko#55]
We are just starting to use FDK on Mac and Linux and seeing many problems with paths, Like this.. Any idea what Im doing wrong? or fix this
`/Users/Pathum/bin/FDK/Tools/osx/makeotf: line 18: /Users/Pathum/bin/FDK/Tools/osx/Python/Current/bin/python: No such file or directory
`

cc @paarandika

**Comment by paarandika** [comment]
When I make FDK use system Python installation on Ubuntu by un-commenting the line in setFDKpaths file above error goes away. But when I call a tool such as "makeotf" it gives the error below.
'''Please re-install the FDK. The executable directory '/home/randika/FDK/Tools/linux' is missing the tools: ['tx', 'makeotfexe'].
for the files referenced by the shell script is missing.'''
The files mentioned above are in the given path and re-installing did not solve the issue.

**Comment by anthrotype** [comment]
The "makeotf" shell script can't find the embedded Python interpreter required to run the "MakeOTF.py" script, because that "Python" subfolder is not actually included in the Github repository. That needs to be built and configured, as explained in "Building the Python interpreter for the FDK", in the "FDK Build Notes.txt":

> the FDK will use the Python interpreter whose path is specified in the file "setFDKPaths" This line can be changed to point to any other Python interpreter program on the system. However, if you choose to use another Python interpreter, you must add the several third party packages.

If you just want to use the afdko without worrying all this, you can just grab the latest release from Adobe's webite: http://www.adobe.com/devnet/opentype/afdko.html

**Comment by anthrotype** [comment]
You just need to set the AFDKO_Python variable in setFDKPaths to point to any Python interpreter of yours. At least, it works for me on OSX.

@paarandika please check if the executable directory '/home/randika/FDK/Tools/linux' is actually missing the tools mentioned in the error. If they are not there, they must be built from source using "Tools/Programs/BuildAllLinux.sh".

**Comment by anthrotype** [comment]
@paarandika Sorry, I didn't read your comment properly.
The problem is that the executable directory is not in your PATH. That's where makeotf is looking for tx and makeotfexe, etc.
So to fix this, you also need to append the executable directory to your $PATH variable in .bash_profile, .profile, or .bashrc.

This is what I get in my OS X .bash_profile after I install the AFDKO from Adobe website:

```sh
# Initialization for FDK command line tools.Mon Jun  2 12:20:50 2014
FDK_EXE="/Users/cosimolupo/bin/FDK/Tools/osx"
PATH=${PATH}:"/Users/cosimolupo/bin/FDK/Tools/osx"
export PATH
export FDK_EXE
```

Point this to the directory where the compiled tx and makeotfexe are, and see if it works then.
Cheers,

C.

**Comment by paarandika** [comment]
I have  .bashrc, .bash_profile and .profile with lines below. I have added the lines to .bash_profile and .bashrc manually later. The .profile was automatically created.
```FDK_EXE="/home/randika/bin/FDK/Tools/linux"
path=$PATH:"/home/randika/bin/FDK/Tools/linux"
export PATH
export FDK_EXE
```
But still the error persists.

**Comment by anthrotype** [comment]
If you export the PATH (all uppercase) variable in .bash_profile, you don't also need to redo it in .profile or bashrc. Try use one of the three.
If you are trying to set up the Github's afdko, but have previously installed the pre-packaged release, you need to comment out any automatically generated lines in your .profile that were created by the install scripts, and replace them with the actual path to the executable directory located inside your git repository.

**Comment by paarandika** [comment]
No I'm trying the prepackaged version

**Comment by anthrotype** [comment]
Oh well, that's supposed to work out of the box... I don't have a Linux machine to test it. Let's see what others come up with.

**Comment by paarandika** [comment]
The issue with Ubuntu is trying run a 32 bit software in a 64 bit Operating System. I could fix that by installing ia32-libs. I think it's the same issue in in the Mac as well.

**Comment by pathumego** [comment]
@anthrotype @paarandika  Thanks!

**Comment by SimonAM** [comment]
I couldn't find ia32-libs in the repository on ubuntu 16.04. 
The following solved it for me.
sudo apt install lib32z1
