### ISSUE TITLE
[question] Why does AFDKO need NAME table items with PID=1 for feature names?

### ISSUE THREAD

**Issue by davelab6** [adobe-type-tools/afdko#58]
NAME table items with PID=1 are no longer needed, since OS X accepts fonts without them and no sane person is using Mac OS 9 in 2015 :)

**Comment by readroberts** [comment]
This is a good point. Mac platform name ID's were actually required not only in Mac OS9, but also in Mac OSX 10.2, but have not been necessary from some years. Dropping the mac PID 1 names would also get rid of all the problems that come from the conflict between how the OpenType Spec says to build Mac font menu names, and how all most of the Adobe fonts build them, due to an ugly hack necessary at the dawn of the OpenType era. Next round of FDK changes, I will fix makeotf to no longer require PID=1 names.

**Comment by davelab6** [comment]
:dart:
