### ISSUE TITLE
Is there a way to manually set the head.xMin/yMin/xMax/yMax value when makeotf generates fonts?

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#683]
In general, BBox is automatically calculated by the font-output-tool. But some applications are BBox-sensitive, an inappropriate BBox value may cause layout error.

Such as Source Han Sans, a few specific glyphs' scale are larger than the global size, so the BBox value is also very large. In Photoshop, this caused glyph metric height abnormal. In Android, if Source Han Sans is the first font in the system fallback list, all text lines will be displayed with incorrectly y-offset.

So what I want to say is, in some cases, we need to manually set the BBox value for the font being created.

_makeotf_ seems to have no ability to override the BBox value. Although we can modify the input-source-font, or the generated-final-font, but these are not convenient. So I strongly suggest to make **BBox value can set in the `feature` file**, use for _makeotf_. Like this:

```
table head {
    FontRevision 1.000;

    //
    xMin 0;
    yMin -120;
    xMax 1000;
    yMax 880;

    // or
    FontBBox 0 -120 1000 880;
} head;
```

**Comment by kenlunde** [comment]
In my opinion, allowing _makeotf_ to overriding the BBox values in the 'head' table is a Very Bad Idea™. If you want to do it that badly, _ttx_ is your friend. Still, I strongly advise against this. It is better to fix the apps than to deform a font resource.

**Comment by kenlunde** [comment]
On the contrary, we should be thankful for fonts such as those provided by the _Source Han_ typeface families, because they expose bad practices in apps that are otherwise masked by conventional FontBBox settings. I have absolutely no regrets about deciding to include the glyphs that resulted in excessively tall FontBBox settings.

We have also deployed commercial fonts that have excessively tall FontBBox settings, such as _Kazuraki_ (かづらき) and _Ten Mincho_ (貂明朝). The former font includes glyphs for U+3031 and U+3032, along with approximately 50 vertical-only hiragana ligatures, which resulted in the following FontBBox array: [-338 -1179 1587 1939]. The latter family's fonts include vertical forms of U+2E3A and U+2E3B, which resulted in the following FontBBox array, which is also excessively wide: [-254 -1050 3099 1810].

And yes, in terms of apps incorrectly using FontBBox values for layout purpose, you are correct that Adobe is guilty, as is Android OS. While I cannot speak for Google about Android OS issues, there are compatibility issues that need to be considered for Adobe apps, mainly involving possible text reflow for existing documents.

**Comment by LIXiangChen** [comment]
@kenlunde I fully understand and agree with what you said. Although manually set BBox is bad, I still hope you (the AFDKO team) can consider this proposal.

The `feature` file is used to overwrite the features or table values of the font. Some items you may not need to set, but once you need it, and it's supported, it will be useful.

Plus _makeotf_ itself, there exist some options for compatibility purposes, such as `-dcs`, `-oldNameID4`. If everything is required to be corrected by the applications, there will be no such thing.

BTW, I'm wondering what is the correct usage of BBox property?

**Comment by kenlunde** [comment]
The FontBBox values aren't really used, but rather serve to record the minimum rectangle in which all of the glyphs will fit if they are overlaid on their origins. OpenType/CFF fonts include a FontBBox array in their 'CFF ' table, and the reason why the four values are necessary in the 'head' table is because TrueType (aka OpenType/TTF) fonts have no other place to record the FontBBox values.

Note that _makeotf_ cannot be expected to override all values, because some of them should not be overridden. In my opinion, the FontBBox values should not be overridden, because doing so can result in a malformed (according to the specification) font. I prefer that we not allow our tools to produce malformed fonts, which is why I suggested using _ttx_ to accomplish what you want.

Based on the discussions here and above, I now defer to my colleagues as to whether the FontBBox values should be overridden via the "features" file.

**Comment by readroberts** [comment]
@LIXiangChen. Are you sure that it is the large Font BBox that directly causes Photoshop to set the line height larger than desired? The direct cause is usually the values of the  hhea.Ascender/Descender on Mac OSX, and the OS/2. winAscent/Descent on Windows. Having a large Font BBox will cause the ascender/descender values to be large unless they are overridden. Note that both hhea.Ascender/Descenderand the OS/2. winAscent/Descent on Windows can be overridden with feature file statements.  Changing the FontBBox to smaller than that some of the glyphs is a bad idea for two reasons. One is that some apps on both Mac and Windows will use the Font Box to calculate the size of the bitmap need for rasterizering, and setting the FontBBox smaller than it should be will clip those glyphs. Another issue is that for CJK fonts in Adobe apps, having the FontBBox be smaller than the glyph size interacts badly with hinting, causing the glyph to be squashed to the FontBbox size. If you do have special case for a specific font, then I suggest using another tool to edit the Fontbox size; this isn't a function I would want to see as an option in makeotf. AS Ken pointed out, you can edit and recompile with 'ttx'. I think that DTL OtMaster will also do this.

**Comment by LIXiangChen** [comment]
![1](https://user-images.githubusercontent.com/8857634/48878128-0e008480-ee41-11e8-932b-95f93fa85eac.png)

@readroberts To make sure that we are talking about the same thing, this is a screenshot of the issue of the SHS, the dark area is the selection, and it's height is incorrect.

Photoshop's selection issue is caused by `CFF.FontBBox`, just fix this one value and you will get the correct result. (Android's situation is seems related to `head.xMin...` instead of `CFF.FontBBox`).

My proposal is to make the `head.xMin...` 4 values and `CFF.FontBBox` (for OTF, forgot to say above) can be override by setting the BBox values in the `table head {}` of the `features` file used for _makeotf_.

**Comment by kenlunde** [comment]
@LIXiangChen An excessively tall—though extending downward—cursor-selection box is clearly an annoyance, but it is not a layout issue _per se_. After playing around with fonts with excessively large FontBBox arrays—_Source Han Sans_, _Source Han Serif_, _Kazuraki_ (commercial), and _Ten Mincho_ (commercial)—I determined that (the latest-and-greatest) Photoshop and Illustrator clearly use the _head.yMin_ value for the lowest point of the cursor selection box. Some other value, possibly _hhea.ascender_, is used for the highest point. Actual line layout does not appear to be affected, unless adding an underline in Photoshop, in which case it is way too low, but not nearly as low as the _head.yMin_ value, but is clearly influenced by it.

**Comment by miguelsousa** [comment]
This is an edge case and the desired results can be achieved by post-processing the font.
