### ISSUE TITLE
Correct way to add glyph to existing font?

### ISSUE THREAD

**Issue by anyong** [adobe-type-tools/afdko#718]
I am trying to add glyphs to Source Han Sans. I was able to compile `SourceHanSansTW-Regular.otf` from source without issue, and using the instructions for modifying or adding glyphs (http://blogs.adobe.com/CCJKType/2012/02/simplifying-cidfont-glyph-corrections.html, http://blogs.adobe.com/CCJKType/files/2012/10/atypi2012-afdko-lunde.pdf) I have tried a few ways to add glyphs which have not been successful as yet. Here is my process so far:

1. Dump all glyphs from `SourceHanSansTW-Regular.otf` using the command: `tx -pdf SourceHanSansTW-Regular.otf glyphs.pdf`
1. Locate a suitable unused `cid` range (beginning at `cid47542` there is a gap of around 10,000 cids, so plenty of room to add glyphs - is this the correct way to assign a new `cid`?)
1. Create a glyph in fontforge: open new fontforge document, create a glyph in the first position, set the unicode value (`u+207a9`), set the name to `cid48000`, and save as a `.pfa`
1. Add the file `extras.map` as listed below
1. Run the commands listed below
1. Dump the glyphs again and check for the glyph in fontforge

After all of those steps, the glyph shows up correctly but with the wrong unicode value - it shows as `u+f9dc` rather than the expected `u+207a9`. Did I miss a step somewhere? Help would be much appreciated, thank you!

```
// extras.map
mergefonts SourceHanSansTW-Regular-Ideographs 0
0 .notdef
48000 cid48000
```

```
// run.sh
mergefonts -cid ../../Regular/cidfontinfo.TW extras.ps extras.map extras.pfa
tx -t1 SourceHanSansTW-Regular.otf cidfont.orig
mergefonts cidfont.ps cidfont-extras.ps cidfont.orig
tx -cff cidfont.ps CFF
sfntedit -a CFF=CFF SourceHanSansTW-Regular.otf
sfntedit -f SourceHanSansTW-Regular.otf
```

**Comment by kenlunde** [comment]
@anyong All looks good except for the following command lines, which should not be used, as you'll be missing the additional mapping:

```
tx -cff cidfont.ps CFF
sfntedit -a CFF=CFF SourceHanSansTW-Regular.otf
sfntedit -f SourceHanSansTW-Regular.otf
```

The additional glyph disturbed the [CID/GID](https://blogs.adobe.com/CCJKType/2012/04/cid-vs-gid.html) mapping, which is why U+F9DC &#xF9DC; shows up.

Keep in mind that the article you referenced is describing how to modify or correct glyphs that are already present in a CID-keyed font. You are adding glyphs, which necessitates rebuilding the font from source.

You will need to modify the appropriate CMap resource, meaning _UniSourceHanSansTW-UTF32-H_, to add a mapping from U+207A9 𠞩 to CID+48000. Use the [cmap-tool.pl](https://github.com/adobe-type-tools/perl-scripts/blob/master/cmap-tool.pl) script for this:

```
perl cmap-tool.pl -e < UniSourceHanSansTW-UTF32-H > temp.tw
```

Insert the following line into _temp.tx_ at the appropriate location (though it really doesn't matter, as the next command line will sort the code points anyway):

```
<000207A9> 48000
```

You can now recompile the CMap resource:

```
perl cmap-tool.pl -e < temp.tw > UniSourceHanSansTW-UTF32-H
```

(UTF-8 and UTF-16 CMap resources will automagically be generated, which you can safely remove.)

You can now rebuild the OTF using the following AFDKO command lines, substituting the variable $dir for the appropriate weight or weights (the _cidfont.ps_ and _UniSourceHanSansTW-UTF32-H_ files should be the modified versions):

```
makeotf -f cidfont.ps.TW -omitMacNames -ff features.TW -fi cidfontinfo.TW -mf ../FontMenuNameDB.SUBSET -r -nS -cs 2 -ch ../UniSourceHanSansTW-UTF32-H -ci ../SourceHanSans_TW_sequences.txt
tx -cff +S -no_futile cidfont.ps.TW CFF.TW
sfntedit -a CFF=CFF.TW SourceHanSansTW-$dir.otf
```

If you don't care about subroutinizing the CFF, you can skip the second and third command lines.
