### ISSUE TITLE
please tell me what  is the problem?

### ISSUE THREAD

**Issue by mhjy** [adobe-type-tools/afdko#723]
I used the AFDKO to develop a OpenType font.  I now can't resolve a problem. I don’t know where is wrong. Can you help me? I don’t know this is problem of my feature or problem of AFDKO(makeotf ). 
problem is discribed  in attach. 
My email : csmhjy@126.com
[This is My feature file.docx](https://github.com/adobe-type-tools/afdko/files/2825472/This.is.My.feature.file.docx)

[GLT_font.GOADB.txt](https://github.com/adobe-type-tools/afdko/files/2825479/GLT_font.GOADB.txt)

**Comment by mhjy** [comment]
in the word2016，the vert feture is correct，in the word2010, part of the vert feature are correct. Why ???

**Comment by mhjy** [comment]
when print or export to PDF, all the vert lookup are incorrect.

**Comment by kenlunde** [comment]
As long as you meant to type the grammatically-incorrect (but understandable) "are is correct" and not "are incorrect," Microsoft obviously made improvements in MS Word 2016, and any difference in behavior between versions of MS Word is something to be taken up with Microsoft.

I also suggest testing the font with other apps that support vertical writing mode, including modern browsers. This may be a bit of a challenge given that Mongolian text is involved, which has its own challenges. I found [this article](https://www.w3.org/International/articles/vertical-text/).

About exporting to PDF, keep in mind that there are multiple ways of doing so. I don't use Windows, but I think that the options are "Save as PDF" and "Print to PDF." You may need to experiment a bit.

Also, keep in mind that your font involves the Mongolian script, which has known issues in virtually all apps. (Also, Unicode experts are currently discussing the encoding model with experts from Inner and Outer Mongolia, and the outcome will affect any existing implementations.)

Lastly, your "features" file specifies **final** glyph names, such as _glyph177_ as the vertical form of _uni203C_, but your GOADB file indicates that you can use the more readable _uni203C.vert_ instead.

**Comment by mhjy** [comment]
I used the name of the character, but the same error occurred.

**Comment by mhjy** [comment]
sub uni3014 by uni3014.vert;    ------The result is incorrect.
sub uni3015 by uni3015.vert;    ------The result is correct.
Why ?

**Comment by kenlunde** [comment]
@mhjy I didn't expect the use of the "friendly" glyph names to change the behavior. The intent was to make your "features" file more human-readable in that the association between the default (horizontal) and vertical forms is clearer.

Does (1) fail in both MS Word 2010 and MS Word 2016? That particular point hasn't been made entirely clear.

As to why (1) fails but (2) doesn't, it is either an MS Word bug, or something to do with applying features to text runs. One thing to try is to declare more language and script tags for _languagesystems_. I am not sure what else to declare other than 'languagesystem latn dflt;' and 'languagesystem cyrl dflt' (because the GOADB file suggests that the glyph set include Latin and Cyrillic). Keep in mind that the characters in question are considered weak-script, meaning that they usually inherit the script of surrounding characters. To this end, please try changing the characters that come before and after the problematic cases, being sure to use different scripts. The issue seems contextual, hence my suggestion to declare other scripts.

**Comment by readroberts** [comment]
@mhjy For a specific pair of substitutions, it is fairly easy to inspect the font and see if there is anything wrong with it that would cause those substitutions to fail. Can you make a test font which show the failures above, and post it?

**Comment by mhjy** [comment]
[test.docx](https://github.com/adobe-type-tools/afdko/files/2834387/test.docx)

**Comment by mhjy** [comment]
I can't upload .ttf file.

**Comment by mhjy** [comment]
I can't upload .ttf file.

**Comment by mhjy** [comment]
i send the ttf file to notifications@github.com

**Comment by readroberts** [comment]
Please send it to rroberts@adobe.com, and I will take a look.

**Comment by mhjy** [comment]
I have sent to rroberts@adobe.com.

**Comment by readroberts** [comment]
Hello mjhy;  I don't see anything wrong in your *.TTF font. The feature file is simple, clear and correct. The cmap table is correct.  

The only thing I notice that is wrong in the sources is in your GOADB file uses names with 'vert' suffix in the third column. This column is meant to be used only for assigning a Unicode value to a glyph, when the final name cannot be parse to generate a correct Unicode value. This works only if the name in the column is in the format "uniXXXX" or uXXXXX. The suffix breaks this. However, this has no negative effect on the font, beyond the fact that the vertical glyphs have no Unicode value assigned.  It is possible that assigning a correct Unicode value to the vertical glyphs will solve your problem but I doubt this.

The only other thing I can think of is that you might try changing the feature name from 'vert' to 'vrt2'. This has supplanted the earlier feature tag. See
https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz#vrt2 .

If neither of these makes a difference, then you need to apply to Microsoft Word technical support.
