### ISSUE TITLE
Can I safely remove the AFDKO CLI tools without breaking it? 

### ISSUE THREAD

**Issue by her** [adobe-type-tools/afdko#74]
When installing ADFKO for SourceCodePro I was disappointed that AFDKO took the liberty of editing my dot files on my behalf, if this is necessary I understand but if not I'd like to know how to remove them. 

As well, is there a list of which dot files are updated with ADFKO calls for the CLI tools so I can revert them?

Thanks!

**Comment by miguelsousa** [comment]
I think that this is the list you're looking for
https://github.com/adobe-type-tools/afdko/blob/master/FDK/FinishInstallOSX#L156-L160

**Comment by her** [comment]
You're amazing thank you so much! This is the exact list I'm looking for. 

`loginPath1 = os.path.join(homeDir, ".login")`

`loginPath2 = os.path.join(homeDir, ".cshrc")`

`loginPath3 = os.path.join(homeDir, ".profile")`

`loginPath4 = os.path.join(homeDir, ".bash_profile")`

`loginPath5 = os.path.join(homeDir, ".zprofile")`

So can I safely edit these paths out from my dot files and maintain the integrity of ADFKO? 

Thanks again!

**Comment by miguelsousa** [comment]
@her you don't have to have all of those files; some of them were probably added by the FDK install script. But you'll have to have at least one of them, and the FDK lines have to be left in there, otherwise the tools may not work properly. The file that you need to keep will depend on the shell that you use. I, for example, use the `bash` shell, so the only file I have is `.bash_profile`.
