### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by miguelsousa** [adobe-type-tools/afdko#741]
After June 30th 2019 the afdko will officially only support Python 3.6+

- [x] Update CI
- [x] Remove py27-specific `pytest.mark.xfail` decorators
- [x] Remove `__future__` imports
- [x] Remove `subprocess32`
- [x] Remove `fontTools.misc.py23` items
- [x] Change `format()` to f-strings
- [ ] Update installation and build-from-source instructions
- [ ] Remove warning notice from README

**Comment by ShikiSuen** [comment]
Since macOS ships older version of Python, please also add some instructions on how to update the default python to 3.6 or newer on June 30th 2019.

**Comment by miguelsousa** [comment]
@ShikiSuen I'd rather not do that because each system is different. I don't want the AFDKO to be responsible for providing instructions for every single configuration.

We've been providing Py3 wheels for a while, so I suggest that between now and June 30th you figure out how to get your system up and running.

On my Mac I installed Py3 via [Homebrew](https://brew.sh/), which also makes it very simple to update Python itself. I also installed Py2 the same way. I avoid the OS-installed Py2.
I assume there are alternative methods, including downloading the installer from [python.org](https://www.python.org/downloads/).

**Comment by ShikiSuen** [comment]
@miguelsousa

Thanks for your reply.

It is a pain in the neck without using VPN to either install or use Homebrew in Mainland PRC. Even if using that, the datastream often gets choked by something wellknown.

I use MacPorts instead, but its configuration of Python is a little bit sophisticated.

Since adding the instructions of how-to-upgrade-python brings inconveniences to you people, then it looks like something must be done by some people to force Apple upgrade the built-in Pythin in future macOS releases. (Also, the bash, the sed, etc., lots of things.)

**Comment by frankrolf** [comment]
IMO this is a completely different problem. The macOS built-in Python has become more and more brittle, and it is difficult to rely on.
In my experience, it always is better to run an alternative Python install, either installed via Homebrew, or as a download from python.org.
