### ISSUE TITLE
subprocess.call

### ISSUE THREAD

**Issue by typemytype** [adobe-type-tools/afdko#77]
When embedding FDK inside RoboFont a `subprocess.call` works fine but the stdout and stderr got lost...

https://github.com/adobe-type-tools/afdko/blob/master/FDK/Tools/SharedData/FDKScripts/FDKUtils.py#L83

Had to change it to `subprocess.Popen` to retrieve stdout and stderr

```Python
popen = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
popenout, popenerr = popen.communicate()
if popenout:
	print popenout
if popenerr:
	print popenerr
```

(I cannot test this on all kinds of environments)

thanks

**Comment by readroberts** [comment]
The problem with this new code is that it echoes the process output only after the process is completed. The reason for the existence of 'runShellCmdLogging()' is to echo process output for a to stdout while the process is running, so that the user will know that something is going on. makeotfexe can take many minutes to run when subroutinizing.  How about if you try the code that it is in makeInstancesUFO.py, lines 255 to 266? If this works for you, I'll change the code in FDKUtils.py to match.

**Comment by miguelsousa** [comment]
The [lines 255 to 266 of makeInstancesUFO.py](https://github.com/adobe-type-tools/afdko/blob/bf904fa97d2cb14c10334a8d7944c5c841f2709f/FDK/Tools/SharedData/FDKScripts/makeInstancesUFO.py#L255-L266) referenced by Read:
```python
	proc = Popen(opList, stdout=PIPE)
while 1:
	output = proc.stdout.readline()
	if output:
		print output,
		logList.append(output)
	if proc.poll() != None:
		output = proc.stdout.readline()
		if output:
			print output,
			logList.append(output)
		break
```

**Comment by readroberts** [comment]
Went ahead and added the new logic to FDKUtils.py.
