### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by MayuraVerma** [adobe-type-tools/afdko#783]
in this example
https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#example-1

        language TRK;
        # This will inherit both the top level default rules - the rules defined
        # before the first 'script' statement, and the script-level default
        # rules for 'latn: all the lookups of this feature defined after the
        # 'script latn' statement, and before the 'language DEU' statement.
        # If 'TRK' were not named here, it would not inherit the default rules
        # for the script 'latn'.

how can this block inherit both the top level default rules?
in my opinion, this should only inherit,  script latn and language TRK

**Comment by readroberts** [comment]
See section 4.b.ii: """The one exception to this rule are the default lookups. There are two levels of default lookups. Rules specified between the start of a feature definition and the first script are added to all language-systems, unless a language statement specifies the exclude_dflt keyword. Rules specified between the occurrence of the script statement and the first language statement other than dflt are added to explicitly specified languages for the current script""". 

I do see some wording that might be confusing. The comments for language DEU and TRK are both correct, but each describe something that happens with both language statements.

**Comment by MayuraVerma** [comment]
still baffles me
why rules under 'language DEU' would apply to only to script 'latn', 'language DEU'
        # The rules above will be placed in a lookup that is registered only
        # under the script 'latn', 'language DEU'
why rules under 'language TRK' would apply to all both top level and script level?
        # This will inherit both the top level default rules - the rules defined
        # before the first 'script' statement, and the script-level default
        # rules for 'latn: all the lookups of this feature defined after the
        # 'script latn' statement, and before the 'language DEU' statement.
        # If 'TRK' were not named here, it would not inherit the default rules
        # for the script 'latn'.

**Comment by readroberts** [comment]
Section 4.b.ii: states that the rules following a 'language' statement, and preceding any other script or language statement,  will be placed in lookups that are registered only under the current script and language. This is true for the rules following both the DEU and the TRK language statements. Although there is a comment about this only under the 'language DEU' statement, the same logic applies to all 'language' statements.

The comment after 'language TRK' statement does not say that "the  rules under 'language TRK' would apply to all both top level and script level". What is does say is that the set of rules defined after 'language TRK' statement will inherit any **previously** defined default rules, both those defined before any other script statement (which get added to all script-language combinations), and those defined after the 'script latn' and before any subsequent language statement. Although there is a comment about this only under the 'language TRK' statement, the same logic applies to all 'language' statements.

The reason for this logic is to allow users to defined globally default rules, so that they do not have to be repeated after every script statement, and also to define default rules specific to a  script, so they do not have to be repeated after every language statement. It is useful to have both levels, as some rules are needed in every languagesystem, and some rules are needed for all languages in a script, but not in any other scripts.
