### ISSUE TITLE
width and height value in <advance> tag

### ISSUE THREAD

**Issue by hatchzo** [adobe-type-tools/afdko#786]
If a ufo file has both height and width values in <advance> tag, AFDKO tools drop the width value from the font. Please check C12139,  C12140, C12141 and C12142 in the attachment, and then `tx -t1 JPSymbol-EL.ufo > JPSymbol-EL.pfa`. The problem produces on `mergefonts` too.

[JPSymbol-EL.ufo.zip](https://github.com/adobe-type-tools/afdko/files/3066635/JPSymbol-EL.ufo.zip)

**Comment by readroberts** [comment]
The problem is deeper than a bug. The reason that tx and mergefonts drop the vertical advance width when they write to *.pfa and *.cff is the the output font format has nowhere to store vertical advances. This is stored only in the OTF vmtx table. A separate process will be needed to fill out a feature file specification of the vmtx table from the vertical advance widths in a UFO.

**Comment by kenlunde** [comment]
@rroberts The issue is that the horizontal advance, which is specified as the second element of `<advance height="1000" width="1000"/>`, is being ignored, resulting in a glyph with a zero-width horizontal advance.
