### ISSUE TITLE
What is the `AdobeCopyright` (fontinfo file) used for?

### ISSUE THREAD

**Issue by LIXiangChen** [adobe-type-tools/afdko#914]
This key determines the value of `CFF.Notice`, I checked _#5176.CFF_, but it seems didn't give the purpose and range of this value.

**Comment by kenlunde** [comment]
The "AdobeCopyright" keyword is used by _mergefonts_ when the "-cid" command-line option is specified with a "cidfontinfo" file as its argument. The strings that make up the "AdobeCopyright" and "Trademark" keywords are concatenated, and are used as the  /FontInfo dictionary /Notice  string.

Though dated (eight years ago), [this](https://blogs.adobe.com/CCJKType/2011/08/cidfontinfo.html) CJK Type Blog article may help. Some of the behavior has since changed, such as what i described in the previous paragraph. The "FamilyName," "Weight," and "FSType" values are now supported by _mergefonts_.

The _mergefonts_ tool is a very convenient way to convert a name-keyed font into a CID-keyed one, hence the ability to reference a "cidfontinfo" file.

**Comment by LIXiangChen** [comment]
@kenlunde Thank you, but what I want to know more is, does the "Notice" field have any practical meaning for a (CID-keyed) OTF? Is there any known program that reads this string? If don't set "AdobeCopyright" and/or "Trademark" keywords (I tried, it makes the "Notice" field not exist in the CFF table, and both _mergefonts_ and _makeotf_ no error occurs), will it cause any problem when use the OTF?

In my opinion, if a field has no practical meaning for the (CID-keyed) OTF, it should be abolished (at least in the documentation mark it as obsolete), or tools automatically fills a "placeholder" value for it, to keep the OTF file clean and understandable.

**Comment by kenlunde** [comment]
@LIXiangChen _Notice_ and other operators that are present in the 'CFF ' table were [dropped](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2#table-19-cff-1-top-dict-operators-not-used-in-cff2) in the 'CFF2' table. CFF2 consists of only outline data, which makes building [Variable Font Collections](https://blogs.adobe.com/CCJKType/2019/02/variable-font-collections.html) easier.

There is a use case whereby the  _Notice_ string of a CFF serves a purpose: PDF embedding. Depending on the PDF creator, a font can be embedded as an 'sfnt' resource with the usual OpenType tables, including a subsetted 'CFF ', or it may be embedded as a stand-alone—and subsetted—CFF. For the latter case, there is nowhere to reference a copyright or trademark string.

**Comment by LIXiangChen** [comment]
@kenlunde That makes sense, thx.
