### ISSUE TITLE
[spec] MarkAttachClass is listed but not used

### ISSUE THREAD

**Issue by khaledhosny** [adobe-type-tools/afdko#994]
`MarkAttachClass` is listed as one of the feature files keywords but it is not actually used anywhere since mark attachment classes are defined with `lookupflag MarkAttachmentType` and not explicitly in the GDEF table.

Likewise makeotfexe grammar defines the keyword but does not use it anywhere AFAICT.

**Comment by iterumllc** [comment]
Yes - the keyword was not otherwise used in the spec and after asking around no one had solid information about the original intention. I therefore didn't include it in the grammar and removed it from the list on an editing pass.

It can always be added back to the docs if and when its added back into the grammar but for now its gone.

**Comment by khaledhosny** [comment]
I think it was supposed to be used with #1004, but it is was under documented and AFAIK unimplemented. I have no objection to dropping it.

**Comment by iterumllc** [comment]
Various folks have been looking through older specs in relation to #1004 and `MarkAttachClass` is a pre -v1.8 keyword that was never removed from the keyword list.
